// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	"math/big"
)

func freeholdBigInt(text string) *big.Int {
	value, ok := new(big.Int).SetString(text, 10)
	if !ok {
		panic("invalid BigInteger literal")
	}
	return value
}

func freeholdBigFloat(text string, precision int64) *big.Float {
	value, ok := new(big.Float).SetPrec(uint(precision)).SetString(text)
	if !ok {
		panic("invalid BigFloat literal")
	}
	return value
}

func freeholdBigFloatFromInteger(value *big.Int, precision int64) *big.Float {
	return new(big.Float).SetPrec(uint(precision)).SetInt(value)
}

func freeholdBigFloatAbs(value *big.Float) *big.Float {
	result := new(big.Float).SetPrec(value.Prec()).Set(value)
	if result.Sign() < 0 {
		result.Neg(result)
	}
	return result
}

func Accumulate(terms int64) *big.Int {
	if !(terms == 3) {
		panic("freehold requires contract failed")
	}
	var total *big.Int = big.NewInt(0)
	i := 0
	for int64(i) < terms {
		nextI := i + 1
		var nextBig *big.Int = big.NewInt(int64(nextI))
		total = new(big.Int).Add(total, nextBig)
		i = nextI
	}
	var freeholdResult *big.Int = total
	if !(freeholdResult.Cmp(big.NewInt(6)) == 0) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func Main() {
	terms := 3
	var total *big.Int = Accumulate(int64(terms))
	if !(total.String() == "6") {
		panic("freehold check failed")
	}
}
