// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package partner_shared

type Address struct {
	CityId int64  `json:"city_id"`
	Label  string `json:"label"`
}

type Order struct {
	Id      int64   `json:"id"`
	Address Address `json:"address"`
}

const NotFound = "NotFound"

func MakeAddress(cityId int64, label string) Address {
	var freeholdResult Address = Address{CityId: cityId, Label: label}
	if !(freeholdResult.CityId == cityId) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func MakeOrder(id int64, address Address) Order {
	var freeholdResult Order = Order{Id: id, Address: address}
	if !(freeholdResult.Address.CityId == address.CityId) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}
