// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package jsonstringifyrecord

import (
	"encoding/json"
	"strings"
)

func freeholdJSONString(value interface{}) string {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(data)
}

type Person struct {
	Name   string `json:"name"`
	Age    int64  `json:"age"`
	Active bool   `json:"active"`
}

func Main() {
	var person Person = Person{Name: "Ada", Age: 37, Active: true}
	var text string = freeholdJSONString(person)
	if !(int64(strings.Index(text, "Ada")) >= 0) {
		panic("freehold check failed")
	}
	if !(int64(strings.Index(text, "37")) >= 0) {
		panic("freehold check failed")
	}
	if !(int64(strings.Index(text, "true")) >= 0) {
		panic("freehold check failed")
	}
}
