// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package commentmarkersinsidestrings

func Text() string {
	var freeholdResult string = "not -- a comment and not /* a block */"
	if !(freeholdResult == "not -- a comment and not /* a block */") {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func Main() {
	var textValue string = Text()
	if !(textValue == "not -- a comment and not /* a block */") {
		panic("freehold check failed")
	}
}
