// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package functionrequires

func Increment(amount int64) int64 {
	if !(amount >= 0) {
		panic("freehold requires contract failed")
	}
	return amount + 1
}
