// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package procedurecontracts

func Accept(amount int64) {
	if !(amount >= 0) {
		panic("freehold requires contract failed")
	}
	if !(amount >= 0) {
		panic("freehold check failed")
	}
}
