// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	"math"
)

func Main() {
	root := math.Sqrt(float64(9.0))
	if !(root == 3.0) {
		panic("freehold check failed")
	}
}
