// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package std_connect_grpc

import (
	"context"
	std_connect_common "freehold.local/std/connect/common"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"net"
	"runtime"
	"strconv"
	"sync"
)

type ResultServerHandleConnectError struct {
	Ok    bool
	Value ServerHandle
	Error string
}

type ResultCallConnectError struct {
	Ok    bool
	Value Call
	Error string
}

type ResultUnaryReplyConnectError struct {
	Ok    bool
	Value UnaryReply
	Error string
}

type ResultStreamHandleConnectError struct {
	Ok    bool
	Value StreamHandle
	Error string
}

type freeholdTask struct {
	fn       func()
	priority int
}

type freeholdWorker struct {
	id         int
	mu         sync.Mutex
	q          []freeholdTask
	sch        *freeholdScheduler
	lastVictim int
}

type freeholdScheduler struct {
	mu          sync.Mutex
	workers     []*freeholdWorker
	workerCount int
	cond        *sync.Cond
	shutdown    bool
	nextWorker  int
}

var globalScheduler *freeholdScheduler
var schedulerOnce sync.Once

func getScheduler() *freeholdScheduler {
	schedulerOnce.Do(func() {
		globalScheduler = newScheduler(runtime.NumCPU())
	})
	return globalScheduler
}

func newScheduler(workerCount int) *freeholdScheduler {
	s := &freeholdScheduler{
		workerCount: workerCount,
	}
	s.cond = sync.NewCond(&s.mu)
	s.workers = make([]*freeholdWorker, workerCount)
	for i := 0; i < workerCount; i++ {
		s.workers[i] = &freeholdWorker{
			id:         i,
			sch:        s,
			lastVictim: i,
		}
	}
	for i := 0; i < workerCount; i++ {
		go s.workers[i].run()
	}
	return s
}

func (s *freeholdScheduler) Schedule(fn func(), priority int) {
	task := freeholdTask{fn: fn, priority: priority}
	s.mu.Lock()
	next := s.nextWorker
	s.nextWorker = (s.nextWorker + 1) % s.workerCount
	s.mu.Unlock()

	w := s.workers[next]
	w.mu.Lock()
	insertIndex := len(w.q)
	for i, t := range w.q {
		if task.priority > t.priority {
			insertIndex = i
			break
		}
	}
	w.q = append(w.q, freeholdTask{})
	copy(w.q[insertIndex+1:], w.q[insertIndex:])
	w.q[insertIndex] = task
	w.mu.Unlock()

	s.cond.Broadcast()
}

func (w *freeholdWorker) run() {
	s := w.sch
	for {
		var task freeholdTask
		found := false

		w.mu.Lock()
		if len(w.q) > 0 {
			task = w.q[0]
			w.q = w.q[1:]
			found = true
		}
		w.mu.Unlock()

		if !found {
			task, found = w.steal()
		}

		if !found {
			s.mu.Lock()
			for !s.shutdown {
				w.mu.Lock()
				if len(w.q) > 0 {
					task = w.q[0]
					w.q = w.q[1:]
					found = true
				}
				w.mu.Unlock()
				if found {
					break
				}

				task, found = w.steal()
				if found {
					break
				}

				s.cond.Wait()
			}
			s.mu.Unlock()
		}

		if s.shutdown {
			return
		}

		if found {
			task.fn()
		}
	}
}

func (w *freeholdWorker) steal() (freeholdTask, bool) {
	s := w.sch
	numWorkers := len(s.workers)
	if numWorkers <= 1 {
		return freeholdTask{}, false
	}
	w.lastVictim = (w.lastVictim + 1) % numWorkers
	if w.lastVictim == w.id {
		w.lastVictim = (w.lastVictim + 1) % numWorkers
	}
	victim := s.workers[w.lastVictim]

	victim.mu.Lock()
	defer victim.mu.Unlock()
	if len(victim.q) > 0 {
		task := victim.q[len(victim.q)-1]
		victim.q = victim.q[:len(victim.q)-1]
		return task, true
	}
	return freeholdTask{}, false
}

type FreeholdScope struct {
	wg       sync.WaitGroup
	ctx      context.Context
	cancel   context.CancelFunc
	priority int
	sem      chan struct{}
}

type FreeholdJoinHandle[T any] struct {
	ch chan T
}

func freeholdSpawn[T any](wg *sync.WaitGroup, priority int, sem chan struct{}, f func() T) FreeholdJoinHandle[T] {
	wg.Add(1)
	ch := make(chan T, 1)
	taskFn := func() {
		defer wg.Done()
		if sem != nil {
			sem <- struct{}{}
			defer func() { <-sem }()
		}
		ch <- f()
	}
	getScheduler().Schedule(taskFn, priority)
	return FreeholdJoinHandle[T]{ch: ch}
}

func freeholdChannelSend[T any](sender chan<- T, value T) bool {
	sender <- value
	return true
}

func freeholdChannelTrySend[T any](sender chan<- T, value T) bool {
	select {
	case sender <- value:
		return true
	default:
		return false
	}
}

func freeholdChannelReceive[T any](receiver <-chan T) T {
	return <-receiver
}

type GrpcUnaryCall struct {
	Method  string
	Payload string
	Reply   chan string
}

type GrpcStreamCall struct {
	Method  string
	Payload string
	Out     chan string
	Done    chan struct{}
}

type grpcServerEntry struct {
	server   *grpc.Server
	listener net.Listener
}

var (
	GrpcUnaryQueue        = make(chan *GrpcUnaryCall, 64)
	GrpcStreamQueue       = make(chan *GrpcStreamCall, 64)
	grpcRegistrarsMu      sync.Mutex
	grpcServiceRegistrars []func(*grpc.Server)
	grpcDispatchersMu     sync.Mutex
	grpcClientDispatchers = make(map[string]func(context.Context, grpc.ClientConnInterface, string) (string, error))
	grpcStreamDispatchers = make(map[string]func(context.Context, grpc.ClientConnInterface, string) ([]string, error))
	grpcServersMu         sync.Mutex
	grpcServers           = make(map[string]*grpcServerEntry)
	grpcServerCounter     int64
	grpcCallsMu           sync.Mutex
	grpcUnaryCalls        = make(map[string]*GrpcUnaryCall)
	grpcStreamCalls       = make(map[string]*GrpcStreamCall)
	grpcCallCounter       int64
)

func RegisterServiceRegistrar(register func(*grpc.Server)) {
	grpcRegistrarsMu.Lock()
	defer grpcRegistrarsMu.Unlock()
	grpcServiceRegistrars = append(grpcServiceRegistrars, register)
}

func RegisterClientDispatcher(method string, dispatch func(context.Context, grpc.ClientConnInterface, string) (string, error)) {
	grpcDispatchersMu.Lock()
	defer grpcDispatchersMu.Unlock()
	grpcClientDispatchers[method] = dispatch
}

func RegisterStreamDispatcher(method string, dispatch func(context.Context, grpc.ClientConnInterface, string) ([]string, error)) {
	grpcDispatchersMu.Lock()
	defer grpcDispatchersMu.Unlock()
	grpcStreamDispatchers[method] = dispatch
}

func EnqueueUnaryCall(call *GrpcUnaryCall) {
	GrpcUnaryQueue <- call
}

func EnqueueStreamCall(call *GrpcStreamCall) {
	GrpcStreamQueue <- call
}

func grpcLookupClientDispatcher(method string) func(context.Context, grpc.ClientConnInterface, string) (string, error) {
	grpcDispatchersMu.Lock()
	defer grpcDispatchersMu.Unlock()
	return grpcClientDispatchers[method]
}

func grpcLookupStreamDispatcher(method string) func(context.Context, grpc.ClientConnInterface, string) ([]string, error) {
	grpcDispatchersMu.Lock()
	defer grpcDispatchersMu.Unlock()
	return grpcStreamDispatchers[method]
}

func registerGrpcServer(server *grpc.Server, listener net.Listener) string {
	grpcServersMu.Lock()
	defer grpcServersMu.Unlock()
	grpcServerCounter++
	id := "grpc-server-" + strconv.FormatInt(grpcServerCounter, 10)
	grpcServers[id] = &grpcServerEntry{server: server, listener: listener}
	return id
}

func takeGrpcServer(id string) *grpcServerEntry {
	grpcServersMu.Lock()
	defer grpcServersMu.Unlock()
	entry := grpcServers[id]
	delete(grpcServers, id)
	return entry
}

func registerUnaryCall(call *GrpcUnaryCall) string {
	grpcCallsMu.Lock()
	defer grpcCallsMu.Unlock()
	grpcCallCounter++
	id := "grpc-call-" + strconv.FormatInt(grpcCallCounter, 10)
	grpcUnaryCalls[id] = call
	return id
}

func takeUnaryCall(id string) *GrpcUnaryCall {
	grpcCallsMu.Lock()
	defer grpcCallsMu.Unlock()
	call := grpcUnaryCalls[id]
	delete(grpcUnaryCalls, id)
	return call
}

func registerStreamCall(call *GrpcStreamCall) string {
	grpcCallsMu.Lock()
	defer grpcCallsMu.Unlock()
	grpcCallCounter++
	id := "grpc-stream-" + strconv.FormatInt(grpcCallCounter, 10)
	grpcStreamCalls[id] = call
	return id
}

func takeStreamCall(id string) *GrpcStreamCall {
	grpcCallsMu.Lock()
	defer grpcCallsMu.Unlock()
	call := grpcStreamCalls[id]
	delete(grpcStreamCalls, id)
	return call
}

type Client struct {
	Endpoint std_connect_common.Endpoint `json:"endpoint"`
}

type ServerHandle struct {
	Id string `json:"id"`
}

type Call struct {
	Id      string `json:"id"`
	Method  string `json:"method"`
	Payload string `json:"payload"`
}

type StreamHandle struct {
	StatusCode   int64         `json:"status_code"`
	MessageCount int64         `json:"message_count"`
	Messages     <-chan string `json:"messages"`
}

type UnaryReply struct {
	Payload string `json:"payload"`
}

func NewClient(endpoint std_connect_common.Endpoint) Client {
	return Client{Endpoint: endpoint}
}

func Serve(endpoint std_connect_common.Endpoint) ResultServerHandleConnectError {
	host := endpoint.Host
	if host == "" {
		host = "127.0.0.1"
	}
	addr := host
	if endpoint.Port > 0 {
		addr = host + ":" + strconv.FormatInt(endpoint.Port, 10)
	}
	listener, err := net.Listen("tcp", addr)
	if err != nil {
		return ResultServerHandleConnectError{Ok: false, Error: err.Error()}
	}
	server := grpc.NewServer()
	grpcRegistrarsMu.Lock()
	for _, register := range grpcServiceRegistrars {
		register(server)
	}
	grpcRegistrarsMu.Unlock()
	id := registerGrpcServer(server, listener)
	go func() {
		_ = server.Serve(listener)
	}()
	return ResultServerHandleConnectError{Ok: true, Value: ServerHandle{Id: id}}
}

func AcceptCall(ctx context.Context, server ServerHandle) ResultCallConnectError {
	select {
	case <-ctx.Done():
		return ResultCallConnectError{Ok: false, Error: ctx.Err().Error()}
	case call := <-GrpcUnaryQueue:
		id := registerUnaryCall(call)
		return ResultCallConnectError{Ok: true, Value: Call{Id: id, Method: call.Method, Payload: call.Payload}}
	}
}

func Respond(ctx context.Context, pending Call, payload string) bool {
	call := takeUnaryCall(pending.Id)
	if call == nil {
		return false
	}
	select {
	case call.Reply <- payload:
		return true
	case <-ctx.Done():
		return false
	}
}

func Unary(ctx context.Context, client Client, method string, payload string) ResultUnaryReplyConnectError {
	host := client.Endpoint.Host
	if host == "" {
		host = "127.0.0.1"
	}
	addr := host
	if client.Endpoint.Port > 0 {
		addr = host + ":" + strconv.FormatInt(client.Endpoint.Port, 10)
	}
	conn, err := grpc.NewClient(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return ResultUnaryReplyConnectError{Ok: false, Error: err.Error()}
	}
	defer conn.Close()
	dispatch := grpcLookupClientDispatcher(method)
	if dispatch == nil {
		return ResultUnaryReplyConnectError{Ok: false, Error: "no client dispatcher for method " + method}
	}
	response, err := dispatch(ctx, conn, payload)
	if err != nil {
		return ResultUnaryReplyConnectError{Ok: false, Error: err.Error()}
	}
	return ResultUnaryReplyConnectError{Ok: true, Value: UnaryReply{Payload: response}}
}

func StopServer(server ServerHandle) {
	entry := takeGrpcServer(server.Id)
	if entry != nil {
		entry.server.Stop()
	}
}

func AcceptStream(ctx context.Context, server ServerHandle) ResultCallConnectError {
	select {
	case <-ctx.Done():
		return ResultCallConnectError{Ok: false, Error: ctx.Err().Error()}
	case call := <-GrpcStreamQueue:
		id := registerStreamCall(call)
		return ResultCallConnectError{Ok: true, Value: Call{Id: id, Method: call.Method, Payload: call.Payload}}
	}
}

func RespondStream(ctx context.Context, pending Call, count int64, messages <-chan string) bool {
	call := takeStreamCall(pending.Id)
	if call == nil {
		return false
	}
	for i := int64(0); i < count; i++ {
		var message string
		select {
		case <-ctx.Done():
			close(call.Out)
			return false
		case message = <-messages:
		}
		select {
		case call.Out <- message:
		case <-call.Done:
			return false
		case <-ctx.Done():
			close(call.Out)
			return false
		}
	}
	close(call.Out)
	return true
}

func OpenStream(ctx context.Context, client Client, method string, payload string) ResultStreamHandleConnectError {
	host := client.Endpoint.Host
	if host == "" {
		host = "127.0.0.1"
	}
	addr := host
	if client.Endpoint.Port > 0 {
		addr = host + ":" + strconv.FormatInt(client.Endpoint.Port, 10)
	}
	conn, err := grpc.NewClient(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return ResultStreamHandleConnectError{Ok: false, Error: err.Error()}
	}
	defer conn.Close()
	dispatch := grpcLookupStreamDispatcher(method)
	if dispatch == nil {
		return ResultStreamHandleConnectError{Ok: false, Error: "no stream dispatcher for method " + method}
	}
	messages, err := dispatch(ctx, conn, payload)
	if err != nil {
		return ResultStreamHandleConnectError{Ok: false, Error: err.Error()}
	}
	buffer := make(chan string, len(messages)+1)
	for _, message := range messages {
		buffer <- message
	}
	close(buffer)
	return ResultStreamHandleConnectError{Ok: true, Value: StreamHandle{StatusCode: 200, MessageCount: int64(len(messages)), Messages: buffer}}
}
