// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package stdiologfdynamicformat

import (
	"fmt"
	"strings"
)

func freeholdStringTemplateWriteText(builder *strings.Builder, text string) {
	if strings.Contains(text, "{}") {
		panic("template placeholder must use ${} instead of {}")
	}
	if strings.ContainsAny(text, "{}") {
		panic("invalid template brace")
	}
	builder.WriteString(text)
}

func freeholdStringTemplateIdent(name string) bool {
	if name == "" {
		return false
	}
	for index := 0; index < len(name); index++ {
		char := name[index]
		letter := (char >= 'A' && char <= 'Z') || (char >= 'a' && char <= 'z') || char == '_'
		digit := char >= '0' && char <= '9'
		if index == 0 {
			if !letter {
				return false
			}
			continue
		}
		if !letter && !digit {
			return false
		}
	}
	return true
}

func freeholdStringTemplate(template string, positional []any, named map[string]any) string {
	var builder strings.Builder
	position := 0
	usedNamed := map[string]bool{}
	sawPositional := false
	sawNamed := false
	for index := 0; index < len(template); {
		start := strings.Index(template[index:], "${")
		if start < 0 {
			freeholdStringTemplateWriteText(&builder, template[index:])
			break
		}
		start += index
		freeholdStringTemplateWriteText(&builder, template[index:start])
		end := strings.Index(template[start+2:], "}")
		if end < 0 {
			panic("invalid string template brace")
		}
		end += start + 2
		placeholder := strings.TrimSpace(template[start+2 : end])
		if placeholder == "" {
			if sawNamed {
				panic("cannot mix positional and named template placeholders")
			}
			sawPositional = true
			if position >= len(positional) {
				panic("string template placeholder count mismatch")
			}
			builder.WriteString(fmt.Sprint(positional[position]))
			position++
		} else {
			if sawPositional {
				panic("cannot mix positional and named template placeholders")
			}
			if !freeholdStringTemplateIdent(placeholder) {
				panic("invalid named template placeholder: ${" + placeholder + "}")
			}
			sawNamed = true
			value, ok := named[placeholder]
			if !ok {
				panic("missing string template binding: " + placeholder)
			}
			usedNamed[placeholder] = true
			builder.WriteString(fmt.Sprint(value))
		}
		index = end + 1
	}
	if position != len(positional) {
		panic("string template placeholder count mismatch")
	}
	for name := range named {
		if !usedNamed[name] {
			panic("unused string template binding: " + name)
		}
	}
	return builder.String()
}

func Main() {
	var format string = "value=${}"
	fmt.Println(freeholdStringTemplate(format, []any{3}, nil))
}
