// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	banking_proofs "freehold.local/banking/proofs"
)

func Main() {
	if !(banking_proofs.BalanceNeverNegative()) {
		panic("freehold check failed")
	}
}
