// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package matrix_bignumberexpression

import (
	"fmt"
	"math/big"
	"strings"
)

func freeholdBigInt(text string) *big.Int {
	value, ok := new(big.Int).SetString(text, 10)
	if !ok {
		panic("invalid BigInteger literal")
	}
	return value
}

func freeholdBigFloat(text string, precision int64) *big.Float {
	value, ok := new(big.Float).SetPrec(uint(precision)).SetString(text)
	if !ok {
		panic("invalid BigFloat literal")
	}
	return value
}

func freeholdBigFloatFromInteger(value *big.Int, precision int64) *big.Float {
	return new(big.Float).SetPrec(uint(precision)).SetInt(value)
}

func freeholdBigFloatAbs(value *big.Float) *big.Float {
	result := new(big.Float).SetPrec(value.Prec()).Set(value)
	if result.Sign() < 0 {
		result.Neg(result)
	}
	return result
}

func Main() {
	base := freeholdBigInt("21")
	doubled := new(big.Int).Mul(base, big.NewInt(2))
	message := fmt.Sprintf("answer=%v", doubled.String())
	if !(int64(strings.Index(message, "42")) >= 0) {
		panic("freehold check failed")
	}
}
