// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package bigimportdeclaration

import (
	"math/big"
)

func freeholdBigInt(text string) *big.Int {
	value, ok := new(big.Int).SetString(text, 10)
	if !ok {
		panic("invalid BigInteger literal")
	}
	return value
}

func freeholdBigFloat(text string, precision int64) *big.Float {
	value, ok := new(big.Float).SetPrec(uint(precision)).SetString(text)
	if !ok {
		panic("invalid BigFloat literal")
	}
	return value
}

func freeholdBigFloatFromInteger(value *big.Int, precision int64) *big.Float {
	return new(big.Float).SetPrec(uint(precision)).SetInt(value)
}

func freeholdBigFloatAbs(value *big.Float) *big.Float {
	result := new(big.Float).SetPrec(value.Prec()).Set(value)
	if result.Sign() < 0 {
		result.Neg(result)
	}
	return result
}

func Main() {
	item := freeholdBigInt("42")
	text := item.String()
	if !(text == "42") {
		panic("freehold check failed")
	}
}
