from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from freehold.core.ast import (
    ArrayLiteralExpr,
    ArrayTypeName,
    AssignStmt,
    BinaryExpr,
    BoolExpr,
    CallStmt,
    CaseStmt,
    CallExpr,
    CheckStmt,
    DoubleExpr,
    ErrorDecl,
    FieldAccessExpr,
    FieldAssignStmt,
    IfStmt,
    ImportDecl,
    IndexExpr,
    LetStmt,
    NumberExpr,
    Param,
    Program,
    RecordLiteralExpr,
    RecordTypeDecl,
    ReturnPlain,
    ReturnOk,
    ReturnError,
    ReturnStmt,
    RoutineDecl,
    ResultTypeName,
    StringExpr,
    TypeDecl,
    TypeName,
    UnaryExpr,
    VarExpr,
    WhileStmt,
    type_to_string,
)
from freehold.core.module_resolver import ModuleResolver, ResolvedModule
from freehold.core.parser import parse_source
from freehold.core.verifier import verify_program


class GoCodegenError(Exception):
    pass


@dataclass(frozen=True)
class GoCodegenResult:
    module_name: str
    package_name: str
    package_path: str
    go_source: str
    supported: bool
    diagnostics: list[dict[str, str]]
    imports: list[dict[str, Any]]

    def to_json(self, source_file: str | None = None, artifact_file: str | None = None, expected_file: str | None = None, status: str | None = None) -> dict[str, Any]:
        data: dict[str, Any] = {
            "module": self.module_name,
            "package": self.package_name,
            "package_path": self.package_path,
            "supported": self.supported,
            "diagnostics": self.diagnostics,
            "imports": self.imports,
            "go_source": self.go_source,
        }
        if source_file is not None:
            data["source_file"] = source_file
        if artifact_file is not None:
            data["artifact_file"] = artifact_file
        if expected_file is not None:
            data["expected_file"] = expected_file
        if status is not None:
            data["status"] = status
        return data


def generate_go_source(source: str) -> GoCodegenResult:
    program = parse_source(source)
    verify_program(program)
    generator = GoGenerator(program)
    return generator.generate()


def generate_go_file(path: str | Path) -> GoCodegenResult:
    source_path = Path(path)
    source = source_path.read_text(encoding="utf-8")
    program = parse_source(source)
    if program.imports:
        resolver = ModuleResolver()
        resolved_modules = resolver.resolve_entry(source_path)
        if resolver.entry is None:
            raise GoCodegenError("module resolver did not produce an entry module")
        generator = GoGenerator(resolver.entry.ast, resolved_modules)
        return generator.generate()
    verify_program(program)
    generator = GoGenerator(program)
    return generator.generate()


def result_json(result: GoCodegenResult, **metadata: str) -> str:
    return json.dumps(result.to_json(**metadata), indent=2) + "\n"


class GoGenerator:
    def __init__(self, program: Program, resolved_modules: dict[str, ResolvedModule] | None = None):
        self.program = program
        self.resolved_modules = resolved_modules or {}
        self.diagnostics: list[dict[str, str]] = []
        self.imports = program.imports or []
        self.local_routines = {declaration.name for declaration in program.declarations if isinstance(declaration, RoutineDecl)}
        self.imports_by_module = {import_decl.module_name: import_decl for import_decl in self.imports}
        self.exposed_symbols = self.build_exposed_symbols(self.imports)
        self.used_import_modules: set[str] = set()
        self.result_types: dict[str, ResultTypeName] = {}
        self.current_return_type: Any = None

    def generate(self) -> GoCodegenResult:
        package_name = go_package_name(self.program.module_name)
        body_lines: list[str] = []
        for declaration in self.program.declarations:
            if isinstance(declaration, TypeDecl):
                body_lines.extend(self.type_decl(declaration))
            elif isinstance(declaration, RecordTypeDecl):
                body_lines.extend(self.record_decl(declaration))
            elif isinstance(declaration, RoutineDecl):
                body_lines.extend(self.routine_decl(declaration))
            elif isinstance(declaration, ErrorDecl):
                body_lines.extend(self.error_decl(declaration))
            else:
                self.unsupported(declaration, "declaration not supported by Go codegen V1")
        lines = [
            "// Code generated by Freehold Go codegen V1; DO NOT EDIT.",
            f"package {package_name}",
            "",
        ]
        lines.extend(self.import_block())
        lines.extend(self.result_type_decls())
        lines.extend(body_lines)
        go_source = format_go_source("\n".join(lines).rstrip() + "\n")
        return GoCodegenResult(
            module_name=self.program.module_name,
            package_name=package_name,
            package_path=go_package_path(self.program.module_name),
            go_source=go_source,
            supported=not self.diagnostics,
            diagnostics=self.diagnostics,
            imports=self.import_metadata(),
        )

    def build_exposed_symbols(self, imports: list[ImportDecl]) -> dict[str, str | None]:
        symbols: dict[str, str | None] = {}
        for import_decl in imports:
            for symbol in import_decl.exposing:
                if symbol in symbols and symbols[symbol] != import_decl.module_name:
                    symbols[symbol] = None
                else:
                    symbols[symbol] = import_decl.module_name
        return symbols

    def import_block(self) -> list[str]:
        used_imports = [import_decl for import_decl in self.imports if import_decl.module_name in self.used_import_modules]
        if not used_imports:
            return []
        lines = ["import ("]
        for import_decl in used_imports:
            lines.append(f"\t{go_import_alias(import_decl.module_name)} \"{go_import_path(import_decl.module_name)}\"")
        lines.extend([")", ""])
        return lines

    def import_metadata(self) -> list[dict[str, Any]]:
        return [
            {
                "module": import_decl.module_name,
                "alias": go_import_alias(import_decl.module_name),
                "path": go_import_path(import_decl.module_name),
                "used": import_decl.module_name in self.used_import_modules,
            }
            for import_decl in self.imports
        ]

    def type_decl(self, declaration: TypeDecl) -> list[str]:
        return [f"type {go_exported_name(declaration.name)} {go_type_string(declaration.base)}", ""]

    def error_decl(self, declaration: ErrorDecl) -> list[str]:
        return [f"const {go_exported_name(declaration.name)} = {json.dumps(declaration.name)}", ""]

    def result_type_decls(self) -> list[str]:
        lines: list[str] = []
        for result_type in self.result_types.values():
            lines.append(f"type {go_result_type_name(result_type)} struct {{")
            lines.append("\tOk bool")
            lines.append(f"\tValue {self.go_type_ref(result_type.ok_type)}")
            lines.append("\tError string")
            lines.extend(["}", ""])
        return lines

    def record_decl(self, declaration: RecordTypeDecl) -> list[str]:
        if declaration.type_params:
            self.unsupported(declaration, "generic records are not supported by Go codegen V1")
            return []
        lines = [f"type {go_exported_name(declaration.name)} struct {{"]
        for field in declaration.fields:
            lines.append(f"\t{go_exported_name(field.name)} {go_type_string(field.type_name)}")
        lines.extend(["}", ""])
        return lines

    def routine_decl(self, routine: RoutineDecl) -> list[str]:
        if routine.type_params:
            self.unsupported(routine, "generic routines are not supported by Go codegen V1")
            return []
        if routine.is_async:
            self.unsupported(routine, "async routines are not supported by Go codegen V1")
            return []
        params = ", ".join(self.param(param) for param in routine.params)
        result_type = "" if routine.return_type is None else f" {self.go_type_ref(routine.return_type)}"
        lines = [f"func {go_exported_name(routine.name)}({params}){result_type} {{"]
        if routine.requires or routine.ensures or routine.aborts:
            self.unsupported(routine, "runtime contracts are not supported by Go codegen V1")
        previous_return_type = self.current_return_type
        self.current_return_type = routine.return_type
        for stmt in routine.body:
            lines.extend(f"\t{line}" for line in self.statement(stmt))
        self.current_return_type = previous_return_type
        lines.extend(["}", ""])
        return lines

    def param(self, param: Param) -> str:
        return f"{go_local_name(param.name)} {go_type_string(param.type_name)}"

    def statement(self, stmt: Any) -> list[str]:
        if isinstance(stmt, LetStmt):
            return [f"{go_local_name(stmt.name)} := {self.expr_with_type(stmt.expr, stmt.type_ref)}"]
        if isinstance(stmt, AssignStmt):
            return [f"{go_local_name(stmt.name)} = {self.expr(stmt.expr)}"]
        if isinstance(stmt, FieldAssignStmt):
            head, *tail = stmt.path
            target = ".".join([go_local_name(head)] + [go_exported_name(part) for part in tail])
            return [f"{target} = {self.expr(stmt.expr)}"]
        if isinstance(stmt, ReturnStmt):
            if isinstance(stmt.value, ReturnPlain):
                return [f"return {self.expr(stmt.value.expr)}"]
            if isinstance(stmt.value, ReturnOk):
                if not isinstance(self.current_return_type, ResultTypeName):
                    self.unsupported(stmt, "return ok requires a Result return type")
                    return ["// unsupported result return"]
                return [
                    f"return {go_result_type_name(self.current_return_type)}{{Ok: true, Value: {self.expr_with_type(stmt.value.expr, self.current_return_type.ok_type)}}}"
                ]
            if isinstance(stmt.value, ReturnError):
                if not isinstance(self.current_return_type, ResultTypeName):
                    self.unsupported(stmt, "return error requires a Result return type")
                    return ["// unsupported result return"]
                return [f"return {go_result_type_name(self.current_return_type)}{{Ok: false, Error: {go_exported_name(stmt.value.error_name)}}}"]
            self.unsupported(stmt, "return form is not supported by Go codegen V1")
            return ["// unsupported return"]
        if isinstance(stmt, CheckStmt):
            return [f"if !({self.expr(stmt.expr)}) {{ panic(\"freehold check failed\") }}"]
        if isinstance(stmt, CallStmt):
            args = ", ".join(self.expr(arg) for arg in stmt.args)
            return [f"{self.callable_name(stmt.name, stmt)}({args})"]
        if isinstance(stmt, IfStmt):
            lines = [f"if {self.expr(stmt.condition)} {{"]
            lines.extend(indent_lines(self.statement_block(stmt.then_body)))
            if stmt.else_body:
                lines.append("} else {")
                lines.extend(indent_lines(self.statement_block(stmt.else_body)))
            lines.append("}")
            return lines
        if isinstance(stmt, WhileStmt):
            lines = [f"for {self.expr(stmt.condition)} {{"]
            lines.extend(indent_lines(self.statement_block(stmt.body)))
            lines.append("}")
            return lines
        if isinstance(stmt, CaseStmt):
            lines = [f"switch {self.expr(stmt.expr)} {{"]
            for branch in stmt.branches:
                lines.append(f"case {self.expr(branch.value)}:")
                lines.extend(indent_lines(self.statement_block(branch.body)))
            if stmt.default_body:
                lines.append("default:")
                lines.extend(indent_lines(self.statement_block(stmt.default_body)))
            lines.append("}")
            return lines
        self.unsupported(stmt, "statement not supported by Go codegen V1")
        return ["// unsupported statement"]

    def statement_block(self, statements: list[Any]) -> list[str]:
        lines: list[str] = []
        for statement in statements:
            lines.extend(self.statement(statement))
        return lines or ["// empty"]

    def expr(self, expr: Any) -> str:
        return self.expr_at(expr, 0)

    def expr_with_type(self, expr: Any, type_ref: Any) -> str:
        if isinstance(expr, ArrayLiteralExpr) and isinstance(type_ref, ArrayTypeName):
            values = ", ".join(self.expr(item) for item in expr.items)
            return f"[{type_ref.size}]{go_type_string(type_ref.element_type)}{{{values}}}"
        return self.expr(expr)

    def go_type_ref(self, type_ref: Any) -> str:
        if isinstance(type_ref, ResultTypeName):
            self.result_types.setdefault(type_to_string(type_ref), type_ref)
        return go_type_ref(type_ref)

    def expr_at(self, expr: Any, parent_precedence: int, side: str = "") -> str:
        if isinstance(expr, NumberExpr):
            return str(expr.value)
        if isinstance(expr, DoubleExpr):
            return repr(expr.value)
        if isinstance(expr, BoolExpr):
            return "true" if expr.value else "false"
        if isinstance(expr, StringExpr):
            return json.dumps(expr.value)
        if isinstance(expr, VarExpr):
            return go_local_name(expr.name)
        if isinstance(expr, FieldAccessExpr):
            head, *tail = expr.path
            parts = [go_local_name(head)] + [go_exported_name(part) for part in tail]
            return ".".join(parts)
        if isinstance(expr, IndexExpr):
            return f"{go_local_name(expr.name)}[{self.expr(expr.index)}]"
        if isinstance(expr, UnaryExpr):
            precedence = unary_precedence(expr.op)
            rendered = f"{go_operator(expr.op)}{self.expr_at(expr.expr, precedence)}"
            return parenthesize_if_needed(rendered, precedence, parent_precedence, side, expr.op)
        if isinstance(expr, BinaryExpr):
            precedence = go_precedence(expr.op)
            rendered = f"{self.expr_at(expr.left, precedence, 'left')} {go_operator(expr.op)} {self.expr_at(expr.right, precedence, 'right')}"
            return parenthesize_if_needed(rendered, precedence, parent_precedence, side, expr.op)
        if isinstance(expr, RecordLiteralExpr):
            args = ", ".join(f"{go_exported_name(arg.name)}: {self.expr(arg.expr)}" for arg in expr.args)
            return f"{go_exported_name(expr.type_name)}{{{args}}}"
        if isinstance(expr, ArrayLiteralExpr):
            values = ", ".join(self.expr(item) for item in expr.items)
            return f"[]any{{{values}}}"
        if isinstance(expr, CallExpr):
            if expr.type_args:
                self.unsupported(expr, "generic calls are not supported by Go codegen V1")
            args = ", ".join(self.expr(arg) for arg in expr.args)
            return f"{self.callable_name(expr.name, expr)}({args})"
        self.unsupported(expr, "expression not supported by Go codegen V1")
        return "nil"

    def callable_name(self, name: str, node: Any) -> str:
        current_prefix = f"{self.program.module_name}."
        if name.startswith(current_prefix):
            return go_exported_name(name[len(current_prefix):])
        for module_name in sorted(self.imports_by_module, key=len, reverse=True):
            prefix = f"{module_name}."
            if name.startswith(prefix):
                symbol_name = name[len(prefix):]
                if "." in symbol_name:
                    self.unsupported(node, f"nested imported routine names are not supported by Go codegen V1: {name}")
                self.used_import_modules.add(module_name)
                return f"{go_import_alias(module_name)}.{go_exported_name(symbol_name)}"
        if "." in name:
            self.unsupported(node, f"qualified call target is not imported by this module: {name}")
            return go_qualified_name(name)
        exposed_module = self.exposed_symbols.get(name)
        if exposed_module is None and name in self.exposed_symbols:
            self.unsupported(node, f"ambiguous exposed symbol in imported modules: {name}")
            return go_exported_name(name)
        if exposed_module is not None and name not in self.local_routines:
            self.used_import_modules.add(exposed_module)
            return f"{go_import_alias(exposed_module)}.{go_exported_name(name)}"
        return go_exported_name(name)

    def unsupported(self, node: Any, message: str) -> None:
        pos = getattr(node, "pos", None)
        location = pos.text() if pos is not None else "line ?:?"
        diagnostic = {
            "code": "FH-GOCODEGEN-0001",
            "message": message,
            "location": location,
        }
        if diagnostic not in self.diagnostics:
            self.diagnostics.append(diagnostic)


def go_type_ref(type_ref: Any) -> str:
    if isinstance(type_ref, TypeName):
        return go_type_string(type_ref.name)
    if isinstance(type_ref, ArrayTypeName):
        return f"[{type_ref.size}]{go_type_string(type_ref.element_type)}"
    if isinstance(type_ref, ResultTypeName):
        return go_result_type_name(type_ref)
    raise GoCodegenError(f"unsupported Go type reference: {type_to_string(type_ref)}")


def go_type_string(type_name: str) -> str:
    generic = parse_generic(type_name)
    if generic is not None:
        base, args = generic
        if base == "Array" and len(args) == 2 and args[1].isdigit():
            return f"[{args[1]}]{go_type_string(args[0])}"
        if base == "Result" and len(args) == 2:
            return go_result_type_name(ResultTypeName(TypeName(args[0]), args[1]))
        if base in {"JoinHandle", "Channel", "Sender", "Receiver"}:
            raise GoCodegenError(f"{base} is not supported by Go codegen V1")
    mapping = {
        "Integer": "int64",
        "Boolean": "bool",
        "Double": "float64",
        "String": "string",
    }
    return mapping.get(type_name, go_exported_name(type_name))


def go_result_type_name(type_ref: ResultTypeName) -> str:
    return f"Result{go_type_name_fragment(type_ref.ok_type)}{go_exported_name(type_ref.error_type)}"


def go_type_name_fragment(type_ref: Any) -> str:
    if isinstance(type_ref, TypeName):
        return go_exported_name(type_ref.name)
    if isinstance(type_ref, ArrayTypeName):
        return f"Array{go_exported_name(type_ref.element_type)}{type_ref.size}"
    if isinstance(type_ref, ResultTypeName):
        return go_result_type_name(type_ref)
    return go_exported_name(type_to_string(type_ref))


def go_package_name(module_name: str) -> str:
    package = re.sub(r"[^A-Za-z0-9_]", "_", module_name).lower()
    if not package or package[0].isdigit():
        return f"fh_{package}"
    return package


def go_package_path(module_name: str) -> str:
    return "/".join(go_package_path_part(part) for part in module_name.split("."))


def go_import_path(module_name: str) -> str:
    return f"freehold.local/{go_package_path(module_name)}"


def go_import_alias(module_name: str) -> str:
    return go_package_name(module_name)


def go_package_path_part(name: str) -> str:
    part = re.sub(r"[^A-Za-z0-9_]", "_", name).lower()
    if not part or part[0].isdigit():
        return f"fh_{part}"
    return part


def go_exported_name(name: str) -> str:
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", name) if part]
    if not parts:
        return "X"
    return "".join(part[:1].upper() + part[1:] for part in parts)


def go_local_name(name: str) -> str:
    exported = go_exported_name(name)
    return exported[:1].lower() + exported[1:]


def go_qualified_name(name: str) -> str:
    return ".".join(go_exported_name(part) for part in name.split("."))


def go_operator(op: str) -> str:
    return {"=": "==", "and": "&&", "or": "||", "not": "!"}.get(op, op)


def go_precedence(op: str) -> int:
    return {
        "or": 1,
        "and": 2,
        "=": 3,
        "!=": 3,
        "<": 3,
        "<=": 3,
        ">": 3,
        ">=": 3,
        "+": 4,
        "-": 4,
        "*": 5,
        "/": 5,
        "not": 6,
    }.get(op, 7)


def unary_precedence(op: str) -> int:
    return 6 if op in {"not", "-"} else go_precedence(op)


def parenthesize_if_needed(rendered: str, precedence: int, parent_precedence: int, side: str, op: str) -> str:
    if precedence < parent_precedence:
        return f"({rendered})"
    if side == "right" and precedence == parent_precedence and op in {"-", "/", "=", "!=", "<", "<=", ">", ">="}:
        return f"({rendered})"
    return rendered


def indent_lines(lines: list[str]) -> list[str]:
    return [f"\t{line}" for line in lines]


def parse_generic(type_name: str) -> tuple[str, list[str]] | None:
    match = re.fullmatch(r"([A-Za-z_][A-Za-z0-9_]*)<(.+)>", type_name.strip())
    if not match:
        return None
    return match.group(1), split_type_args(match.group(2))


def format_go_source(source: str) -> str:
    try:
        completed = subprocess.run(
            ["gofmt"],
            input=source,
            text=True,
            capture_output=True,
            check=True,
        )
        return completed.stdout
    except Exception:
        return source


def split_type_args(text: str) -> list[str]:
    args: list[str] = []
    depth = 0
    start = 0
    for index, char in enumerate(text):
        if char == "<":
            depth += 1
        elif char == ">":
            depth -= 1
        elif char == "," and depth == 0:
            args.append(text[start:index].strip())
            start = index + 1
    args.append(text[start:].strip())
    return args
