from __future__ import annotations

from pathlib import Path

from freehold.core.ast import Program, ServiceDecl
from freehold.core.go_codegen import (
    GO_PROJECT_MODULE_PATH,
    format_go_source,
    go_exported_name,
    go_import_path,
    go_local_name,
    go_package_name,
    go_package_path,
)
from freehold.core.parser import parse_source
from freehold.core.verifier import VerifiedProgram, verify_program


def generate_grpc_go_bindings(program: Program, verified: VerifiedProgram | None = None) -> str:
    if verified is None:
        verified = verify_program(program)

    services = [declaration for declaration in program.declarations if isinstance(declaration, ServiceDecl)]
    package_name = f"{go_package_name(program.module_name)}_grpc"
    pb_import_path = grpc_pb_import_path(program.module_name)

    lines: list[str] = [
        "// Code generated by Freehold gRPC Go binding codegen V1; DO NOT EDIT.",
        f"package {package_name}",
        "",
    ]

    if not services:
        return format_go_source("\n".join(lines).rstrip() + "\n")

    lines.extend([
        "import (",
        "\t\"context\"",
        "\t\"errors\"",
        "",
        f"\tpb \"{pb_import_path}\"",
        "\t\"google.golang.org/grpc\"",
        "\t\"google.golang.org/grpc/codes\"",
        "\t\"google.golang.org/grpc/metadata\"",
        "\t\"google.golang.org/grpc/status\"",
        ")",
        "",
    ])

    for service in services:
        lines.extend(service_binding(service))

    lines.extend(status_mapping_helper())

    return format_go_source("\n".join(lines).rstrip() + "\n")


def service_binding(service: ServiceDecl) -> list[str]:
    service_name = go_exported_name(service.name)
    handler_name = f"{service_name}Handler"
    server_name = f"{service_name}Server"
    client_interface_name = f"{service_name}Client"
    client_struct_name = service_name[0].lower() + service_name[1:] + "Client"
    
    # 1. Server Handler Interface
    lines: list[str] = [
        f"type {handler_name} interface {{",
    ]
    for rpc in service.rpcs:
        method_name = go_exported_name(rpc.name)
        req_type = go_exported_name(rpc.request_type)
        resp_type = go_exported_name(rpc.response_type)
        
        is_req_stream = getattr(rpc, "request_stream", False)
        is_resp_stream = getattr(rpc, "response_stream", False)
        
        if not is_req_stream and not is_resp_stream:
            # Unary
            lines.append(f"\t{method_name}(ctx context.Context, request *pb.{req_type}) (*pb.{resp_type}, error)")
        elif not is_req_stream and is_resp_stream:
            # Server-side streaming
            lines.append(f"\t{method_name}(request *pb.{req_type}, stream pb.{service_name}_{method_name}Server) error")
        elif is_req_stream and not is_resp_stream:
            # Client-side streaming
            lines.append(f"\t{method_name}(stream pb.{service_name}_{method_name}Server) error")
        else:
            # Bidirectional streaming
            lines.append(f"\t{method_name}(stream pb.{service_name}_{method_name}Server) error")
            
    lines.extend([
        "}",
        "",
        f"type {server_name} struct {{",
        f"\tpb.Unimplemented{service_name}Server",
        f"\thandler {handler_name}",
        "}",
        "",
        f"func New{server_name}(handler {handler_name}) *{server_name} {{",
        "\tif handler == nil {",
        f"\t\tpanic(\"nil {handler_name}\")",
        "\t}",
        f"\treturn &{server_name}{{handler: handler}}",
        "}",
        "",
        f"func Register{service_name}Server(registrar grpc.ServiceRegistrar, handler {handler_name}) {{",
        f"\tpb.Register{service_name}Server(registrar, New{server_name}(handler))",
        "}",
        "",
    ])
    
    # 2. Server implementation methods
    for rpc in service.rpcs:
        method_name = go_exported_name(rpc.name)
        req_type = go_exported_name(rpc.request_type)
        resp_type = go_exported_name(rpc.response_type)
        is_req_stream = getattr(rpc, "request_stream", False)
        is_resp_stream = getattr(rpc, "response_stream", False)
        
        if not is_req_stream and not is_resp_stream:
            # Unary
            lines.extend([
                f"func (server *{server_name}) {method_name}(ctx context.Context, request *pb.{req_type}) (*pb.{resp_type}, error) {{",
                f"\tresponse, err := server.handler.{method_name}(ctx, request)",
                "\tif err != nil {",
                "\t\treturn nil, freeholdGrpcStatus(ctx, err)",
                "\t}",
                "\treturn response, nil",
                "}",
                "",
            ])
        elif not is_req_stream and is_resp_stream:
            # Server-side streaming
            lines.extend([
                f"func (server *{server_name}) {method_name}(request *pb.{req_type}, stream pb.{service_name}_{method_name}Server) error {{",
                f"\terr := server.handler.{method_name}(request, stream)",
                "\tif err != nil {",
                "\t\treturn freeholdGrpcStatus(stream.Context(), err)",
                "\t}",
                "\treturn nil",
                "}",
                "",
            ])
        elif is_req_stream and not is_resp_stream:
            # Client-side streaming
            lines.extend([
                f"func (server *{server_name}) {method_name}(stream pb.{service_name}_{method_name}Server) error {{",
                f"\terr := server.handler.{method_name}(stream)",
                "\tif err != nil {",
                "\t\treturn freeholdGrpcStatus(stream.Context(), err)",
                "\t}",
                "\treturn nil",
                "}",
                "",
            ])
        else:
            # Bidirectional streaming
            lines.extend([
                f"func (server *{server_name}) {method_name}(stream pb.{service_name}_{method_name}Server) error {{",
                f"\terr := server.handler.{method_name}(stream)",
                "\tif err != nil {",
                "\t\treturn freeholdGrpcStatus(stream.Context(), err)",
                "\t}",
                "\treturn nil",
                "}",
                "",
            ])
            
    # 3. Client Interface
    lines.extend([
        f"type {client_interface_name} interface {{",
    ])
    for rpc in service.rpcs:
        method_name = go_exported_name(rpc.name)
        req_type = go_exported_name(rpc.request_type)
        resp_type = go_exported_name(rpc.response_type)
        is_req_stream = getattr(rpc, "request_stream", False)
        is_resp_stream = getattr(rpc, "response_stream", False)
        
        if not is_req_stream and not is_resp_stream:
            # Unary
            lines.append(f"\t{method_name}(ctx context.Context, request *pb.{req_type}, opts ...grpc.CallOption) (*pb.{resp_type}, error)")
        elif not is_req_stream and is_resp_stream:
            # Server streaming
            lines.append(f"\t{method_name}(ctx context.Context, request *pb.{req_type}, opts ...grpc.CallOption) (pb.{service_name}_{method_name}Client, error)")
        elif is_req_stream and not is_resp_stream:
            # Client streaming
            lines.append(f"\t{method_name}(ctx context.Context, opts ...grpc.CallOption) (pb.{service_name}_{method_name}Client, error)")
        else:
            # Bidirectional streaming
            lines.append(f"\t{method_name}(ctx context.Context, opts ...grpc.CallOption) (pb.{service_name}_{method_name}Client, error)")
            
    lines.extend([
        "}",
        "",
        f"type {client_struct_name} struct {{",
        f"\tclient pb.{client_interface_name}",
        "}",
        "",
        f"func New{client_interface_name}(cc grpc.ClientConnInterface) {client_interface_name} {{",
        f"\treturn &{client_struct_name}{{client: pb.New{client_interface_name}(cc)}}",
        "}",
        "",
    ])
    
    # 4. Client struct implementation methods
    for rpc in service.rpcs:
        method_name = go_exported_name(rpc.name)
        req_type = go_exported_name(rpc.request_type)
        resp_type = go_exported_name(rpc.response_type)
        is_req_stream = getattr(rpc, "request_stream", False)
        is_resp_stream = getattr(rpc, "response_stream", False)
        
        if not is_req_stream and not is_resp_stream:
            lines.extend([
                f"func (c *{client_struct_name}) {method_name}(ctx context.Context, request *pb.{req_type}, opts ...grpc.CallOption) (*pb.{resp_type}, error) {{",
                f"\tresp, err := c.client.{method_name}(ctx, request, opts...)",
                "\tif err != nil {",
                "\t\treturn nil, freeholdGrpcStatus(ctx, err)",
                "\t}",
                "\treturn resp, nil",
                "}",
                "",
            ])
        elif not is_req_stream and is_resp_stream:
            lines.extend([
                f"func (c *{client_struct_name}) {method_name}(ctx context.Context, request *pb.{req_type}, opts ...grpc.CallOption) (pb.{service_name}_{method_name}Client, error) {{",
                f"\tstream, err := c.client.{method_name}(ctx, request, opts...)",
                "\tif err != nil {",
                "\t\treturn nil, freeholdGrpcStatus(ctx, err)",
                "\t}",
                "\treturn stream, nil",
                "}",
                "",
            ])
        else:
            lines.extend([
                f"func (c *{client_struct_name}) {method_name}(ctx context.Context, opts ...grpc.CallOption) (pb.{service_name}_{method_name}Client, error) {{",
                f"\tstream, err := c.client.{method_name}(ctx, opts...)",
                "\tif err != nil {",
                "\t\treturn nil, freeholdGrpcStatus(ctx, err)",
                "\t}",
                "\treturn stream, nil",
                "}",
                "",
            ])
            
    return lines


def status_mapping_helper() -> list[str]:
    return [
        "type FreeholdGrpcErrorMapping struct {",
        "\tCode     codes.Code",
        "\tMetadata map[string]string",
        "}",
        "",
        "var FreeholdGrpcErrorRegistry = map[string]FreeholdGrpcErrorMapping{}",
        "",
        "func freeholdGrpcStatus(ctx context.Context, err error) error {",
        "\tif err == nil {",
        "\t\treturn nil",
        "\t}",
        "\tvar unwrappedErr = err",
        "\tfor unwrappedErr != nil {",
        "\t\tmsg := unwrappedErr.Error()",
        "\t\tif mapping, ok := FreeholdGrpcErrorRegistry[msg]; ok {",
        "\t\t\tif ctx != nil && len(mapping.Metadata) > 0 {",
        "\t\t\t\tmd := metadata.New(mapping.Metadata)",
        "\t\t\t\t_ = grpc.SendHeader(ctx, md)",
        "\t\t\t}",
        "\t\t\treturn status.Error(mapping.Code, msg)",
        "\t\t}",
        "\t\tunwrappedErr = errors.Unwrap(unwrappedErr)",
        "\t}",
        "\tif _, ok := status.FromError(err); ok {",
        "\t\treturn err",
        "\t}",
        "\tif errors.Is(err, context.Canceled) {",
        "\t\treturn status.Error(codes.Canceled, err.Error())",
        "\t}",
        "\tif errors.Is(err, context.DeadlineExceeded) {",
        "\t\treturn status.Error(codes.DeadlineExceeded, err.Error())",
        "\t}",
        "\treturn status.Error(codes.Unknown, err.Error())",
        "}",
        "",
    ]


def grpc_pb_import_path(module_name: str) -> str:
    return f"{GO_PROJECT_MODULE_PATH}/grpc/{go_package_path(module_name)}pb"


def generate_grpc_go_bindings_source(source: str) -> str:
    program = parse_source(source)
    verified = verify_program(program)
    return generate_grpc_go_bindings(program, verified)


def generate_grpc_go_bindings_file(path: str | Path) -> str:
    source = Path(path).read_text(encoding="utf-8")
    return generate_grpc_go_bindings_source(source)


def grpc_runtime_import_path() -> str:
    return f"{GO_PROJECT_MODULE_PATH}/std/connect/grpc"


def generate_grpc_runtime_glue(program: Program, verified: VerifiedProgram | None = None) -> str:
    """Generate per-service runtime glue that bridges the generated bindings to the
    native Std.Connect.Grpc pull-based runtime (server handler adapter + client dispatchers)."""
    if verified is None:
        verified = verify_program(program)

    services = [declaration for declaration in program.declarations if isinstance(declaration, ServiceDecl)]
    package_name = f"{go_package_name(program.module_name)}_grpc"

    if not services:
        return format_go_source(f"package {package_name}\n")

    pb_import_path = grpc_pb_import_path(program.module_name)
    runtime_path = grpc_runtime_import_path()

    def is_unary(rpc) -> bool:
        return not getattr(rpc, "request_stream", False) and not getattr(rpc, "response_stream", False)

    def is_server_stream(rpc) -> bool:
        return not getattr(rpc, "request_stream", False) and getattr(rpc, "response_stream", False)

    has_server_stream = any(is_server_stream(rpc) for service in services for rpc in service.rpcs)

    lines: list[str] = [
        "// Code generated by Freehold gRPC Go runtime glue codegen V1; DO NOT EDIT.",
        f"package {package_name}",
        "",
        "import (",
        "\t\"context\"",
        "\t\"encoding/json\"",
    ]
    if has_server_stream:
        lines.append("\t\"io\"")
    lines.extend([
        "",
        f"\tpb \"{pb_import_path}\"",
        f"\tgrpcrt \"{runtime_path}\"",
        "\t\"google.golang.org/grpc\"",
        ")",
        "",
    ])

    for service in services:
        service_name = go_exported_name(service.name)
        adapter = go_local_name(service.name) + "RuntimeAdapter"
        lines.append(f"type {adapter} struct{{}}")
        lines.append("")
        for rpc in service.rpcs:
            method_name = go_exported_name(rpc.name)
            req_type = go_exported_name(rpc.request_type)
            resp_type = go_exported_name(rpc.response_type)
            if is_unary(rpc):
                lines.extend([
                    f"func ({adapter}) {method_name}(ctx context.Context, request *pb.{req_type}) (*pb.{resp_type}, error) {{",
                    "\tpayload, err := json.Marshal(request)",
                    "\tif err != nil {",
                    "\t\treturn nil, err",
                    "\t}",
                    "\treply := make(chan string, 1)",
                    f"\tgrpcrt.EnqueueUnaryCall(&grpcrt.GrpcUnaryCall{{Method: \"{rpc.name}\", Payload: string(payload), Reply: reply}})",
                    "\tselect {",
                    "\tcase <-ctx.Done():",
                    "\t\treturn nil, ctx.Err()",
                    "\tcase responsePayload := <-reply:",
                    f"\t\tresponse := new(pb.{resp_type})",
                    "\t\tif err := json.Unmarshal([]byte(responsePayload), response); err != nil {",
                    "\t\t\treturn nil, err",
                    "\t\t}",
                    "\t\treturn response, nil",
                    "\t}",
                    "}",
                    "",
                ])
            elif is_server_stream(rpc):
                lines.extend([
                    f"func ({adapter}) {method_name}(request *pb.{req_type}, stream pb.{service_name}_{method_name}Server) error {{",
                    "\tpayload, err := json.Marshal(request)",
                    "\tif err != nil {",
                    "\t\treturn err",
                    "\t}",
                    "\tout := make(chan string)",
                    "\tdone := make(chan struct{})",
                    f"\tgrpcrt.EnqueueStreamCall(&grpcrt.GrpcStreamCall{{Method: \"{rpc.name}\", Payload: string(payload), Out: out, Done: done}})",
                    "\tfor message := range out {",
                    f"\t\tresponse := new(pb.{resp_type})",
                    "\t\tif err := json.Unmarshal([]byte(message), response); err != nil {",
                    "\t\t\tclose(done)",
                    "\t\t\treturn err",
                    "\t\t}",
                    "\t\tif err := stream.Send(response); err != nil {",
                    "\t\t\tclose(done)",
                    "\t\t\treturn err",
                    "\t\t}",
                    "\t}",
                    "\treturn nil",
                    "}",
                    "",
                ])

    lines.append("func init() {")
    for service in services:
        service_name = go_exported_name(service.name)
        adapter = go_local_name(service.name) + "RuntimeAdapter"
        lines.extend([
            "\tgrpcrt.RegisterServiceRegistrar(func(server *grpc.Server) {",
            f"\t\tRegister{service_name}Server(server, {adapter}{{}})",
            "\t})",
        ])
        for rpc in service.rpcs:
            method_name = go_exported_name(rpc.name)
            req_type = go_exported_name(rpc.request_type)
            if is_unary(rpc):
                lines.extend([
                    f"\tgrpcrt.RegisterClientDispatcher(\"{rpc.name}\", func(ctx context.Context, cc grpc.ClientConnInterface, payload string) (string, error) {{",
                    f"\t\trequest := new(pb.{req_type})",
                    "\t\tif err := json.Unmarshal([]byte(payload), request); err != nil {",
                    "\t\t\treturn \"\", err",
                    "\t\t}",
                    f"\t\tclient := New{service_name}Client(cc)",
                    f"\t\tresponse, err := client.{method_name}(ctx, request)",
                    "\t\tif err != nil {",
                    "\t\t\treturn \"\", err",
                    "\t\t}",
                    "\t\tencoded, err := json.Marshal(response)",
                    "\t\tif err != nil {",
                    "\t\t\treturn \"\", err",
                    "\t\t}",
                    "\t\treturn string(encoded), nil",
                    "\t})",
                ])
            elif is_server_stream(rpc):
                lines.extend([
                    f"\tgrpcrt.RegisterStreamDispatcher(\"{rpc.name}\", func(ctx context.Context, cc grpc.ClientConnInterface, payload string) ([]string, error) {{",
                    f"\t\trequest := new(pb.{req_type})",
                    "\t\tif err := json.Unmarshal([]byte(payload), request); err != nil {",
                    "\t\t\treturn nil, err",
                    "\t\t}",
                    f"\t\tclient := New{service_name}Client(cc)",
                    f"\t\tstream, err := client.{method_name}(ctx, request)",
                    "\t\tif err != nil {",
                    "\t\t\treturn nil, err",
                    "\t\t}",
                    "\t\tvar messages []string",
                    "\t\tfor {",
                    "\t\t\tmessage, err := stream.Recv()",
                    "\t\t\tif err == io.EOF {",
                    "\t\t\t\tbreak",
                    "\t\t\t}",
                    "\t\t\tif err != nil {",
                    "\t\t\t\treturn nil, err",
                    "\t\t\t}",
                    "\t\t\tencoded, err := json.Marshal(message)",
                    "\t\t\tif err != nil {",
                    "\t\t\t\treturn nil, err",
                    "\t\t\t}",
                    "\t\t\tmessages = append(messages, string(encoded))",
                    "\t\t}",
                    "\t\treturn messages, nil",
                    "\t})",
                ])
    lines.append("}")
    lines.append("")

    return format_go_source("\n".join(lines).rstrip() + "\n")