from __future__ import annotations

from pathlib import Path

from freehold.core.ast import Program, ServiceDecl
from freehold.core.go_codegen import (
    GO_PROJECT_MODULE_PATH,
    format_go_source,
    go_exported_name,
    go_package_name,
    go_package_path,
)
from freehold.core.parser import parse_source
from freehold.core.verifier import VerifiedProgram, verify_program


def generate_grpc_go_bindings(program: Program, verified: VerifiedProgram | None = None) -> str:
    if verified is None:
        verified = verify_program(program)

    services = [declaration for declaration in program.declarations if isinstance(declaration, ServiceDecl)]
    package_name = f"{go_package_name(program.module_name)}_grpc"
    pb_import_path = grpc_pb_import_path(program.module_name)

    lines: list[str] = [
        "// Code generated by Freehold gRPC Go binding codegen V1; DO NOT EDIT.",
        f"package {package_name}",
        "",
    ]

    if not services:
        return format_go_source("\n".join(lines).rstrip() + "\n")

    lines.extend([
        "import (",
        "\t\"context\"",
        "\t\"errors\"",
        "",
        f"\tpb \"{pb_import_path}\"",
        "\t\"google.golang.org/grpc\"",
        "\t\"google.golang.org/grpc/codes\"",
        "\t\"google.golang.org/grpc/status\"",
        ")",
        "",
    ])

    for service in services:
        lines.extend(service_binding(service))

    lines.extend(status_mapping_helper())

    return format_go_source("\n".join(lines).rstrip() + "\n")


def service_binding(service: ServiceDecl) -> list[str]:
    service_name = go_exported_name(service.name)
    handler_name = f"{service_name}Handler"
    server_name = f"{service_name}Server"
    lines: list[str] = [
        f"type {handler_name} interface {{",
    ]
    for rpc in service.rpcs:
        lines.append(f"\t{go_exported_name(rpc.name)}(ctx context.Context, request *pb.{go_exported_name(rpc.request_type)}) (*pb.{go_exported_name(rpc.response_type)}, error)")
    lines.extend([
        "}",
        "",
        f"type {server_name} struct {{",
        f"\tpb.Unimplemented{service_name}Server",
        f"\thandler {handler_name}",
        "}",
        "",
        f"func New{server_name}(handler {handler_name}) *{server_name} {{",
        "\tif handler == nil {",
        f"\t\tpanic(\"nil {handler_name}\")",
        "\t}",
        f"\treturn &{server_name}{{handler: handler}}",
        "}",
        "",
        f"func Register{service_name}Server(registrar grpc.ServiceRegistrar, handler {handler_name}) {{",
        f"\tpb.Register{service_name}Server(registrar, New{server_name}(handler))",
        "}",
        "",
    ])
    for rpc in service.rpcs:
        method_name = go_exported_name(rpc.name)
        request_name = go_exported_name(rpc.request_type)
        response_name = go_exported_name(rpc.response_type)
        lines.extend([
            f"func (server *{server_name}) {method_name}(ctx context.Context, request *pb.{request_name}) (*pb.{response_name}, error) {{",
            f"\tresponse, err := server.handler.{method_name}(ctx, request)",
            "\tif err != nil {",
            "\t\treturn nil, freeholdGrpcStatus(err)",
            "\t}",
            "\treturn response, nil",
            "}",
            "",
        ])
    return lines


def status_mapping_helper() -> list[str]:
    return [
        "func freeholdGrpcStatus(err error) error {",
        "\tif err == nil {",
        "\t\treturn nil",
        "\t}",
        "\tif _, ok := status.FromError(err); ok {",
        "\t\treturn err",
        "\t}",
        "\tif errors.Is(err, context.Canceled) {",
        "\t\treturn status.Error(codes.Canceled, err.Error())",
        "\t}",
        "\tif errors.Is(err, context.DeadlineExceeded) {",
        "\t\treturn status.Error(codes.DeadlineExceeded, err.Error())",
        "\t}",
        "\treturn status.Error(codes.Unknown, err.Error())",
        "}",
        "",
    ]


def grpc_pb_import_path(module_name: str) -> str:
    return f"{GO_PROJECT_MODULE_PATH}/grpc/{go_package_path(module_name)}pb"


def generate_grpc_go_bindings_source(source: str) -> str:
    program = parse_source(source)
    verified = verify_program(program)
    return generate_grpc_go_bindings(program, verified)


def generate_grpc_go_bindings_file(path: str | Path) -> str:
    source = Path(path).read_text(encoding="utf-8")
    return generate_grpc_go_bindings_source(source)