// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	"context"
	"encoding/json"
	"fmt"
	app_contract "freehold.local/app/contract"
	std_connect_common "freehold.local/std/connect/common"
	std_connect_grpc "freehold.local/std/connect/grpc"
	"io"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"sync"
)

type ResultUserRequestSchemaError struct {
	Ok    bool
	Value app_contract.UserRequest
	Error string
}

type ResultUserResponseSchemaError struct {
	Ok    bool
	Value app_contract.UserResponse
	Error string
}

type freeholdTask struct {
	fn       func()
	priority int
}

type freeholdWorker struct {
	id         int
	mu         sync.Mutex
	q          []freeholdTask
	sch        *freeholdScheduler
	lastVictim int
}

type freeholdScheduler struct {
	mu          sync.Mutex
	workers     []*freeholdWorker
	workerCount int
	cond        *sync.Cond
	shutdown    bool
	nextWorker  int
}

var globalScheduler *freeholdScheduler
var schedulerOnce sync.Once

func getScheduler() *freeholdScheduler {
	schedulerOnce.Do(func() {
		globalScheduler = newScheduler(runtime.NumCPU())
	})
	return globalScheduler
}

func newScheduler(workerCount int) *freeholdScheduler {
	s := &freeholdScheduler{
		workerCount: workerCount,
	}
	s.cond = sync.NewCond(&s.mu)
	s.workers = make([]*freeholdWorker, workerCount)
	for i := 0; i < workerCount; i++ {
		s.workers[i] = &freeholdWorker{
			id:         i,
			sch:        s,
			lastVictim: i,
		}
	}
	for i := 0; i < workerCount; i++ {
		go s.workers[i].run()
	}
	return s
}

func (s *freeholdScheduler) Schedule(fn func(), priority int) {
	task := freeholdTask{fn: fn, priority: priority}
	s.mu.Lock()
	next := s.nextWorker
	s.nextWorker = (s.nextWorker + 1) % s.workerCount
	s.mu.Unlock()

	w := s.workers[next]
	w.mu.Lock()
	insertIndex := len(w.q)
	for i, t := range w.q {
		if task.priority > t.priority {
			insertIndex = i
			break
		}
	}
	w.q = append(w.q, freeholdTask{})
	copy(w.q[insertIndex+1:], w.q[insertIndex:])
	w.q[insertIndex] = task
	w.mu.Unlock()

	s.cond.Broadcast()
}

func (w *freeholdWorker) run() {
	s := w.sch
	for {
		var task freeholdTask
		found := false

		w.mu.Lock()
		if len(w.q) > 0 {
			task = w.q[0]
			w.q = w.q[1:]
			found = true
		}
		w.mu.Unlock()

		if !found {
			task, found = w.steal()
		}

		if !found {
			s.mu.Lock()
			for !s.shutdown {
				w.mu.Lock()
				if len(w.q) > 0 {
					task = w.q[0]
					w.q = w.q[1:]
					found = true
				}
				w.mu.Unlock()
				if found {
					break
				}

				task, found = w.steal()
				if found {
					break
				}

				s.cond.Wait()
			}
			s.mu.Unlock()
		}

		if s.shutdown {
			return
		}

		if found {
			task.fn()
		}
	}
}

func (w *freeholdWorker) steal() (freeholdTask, bool) {
	s := w.sch
	numWorkers := len(s.workers)
	if numWorkers <= 1 {
		return freeholdTask{}, false
	}
	w.lastVictim = (w.lastVictim + 1) % numWorkers
	if w.lastVictim == w.id {
		w.lastVictim = (w.lastVictim + 1) % numWorkers
	}
	victim := s.workers[w.lastVictim]

	victim.mu.Lock()
	defer victim.mu.Unlock()
	if len(victim.q) > 0 {
		task := victim.q[len(victim.q)-1]
		victim.q = victim.q[:len(victim.q)-1]
		return task, true
	}
	return freeholdTask{}, false
}

type FreeholdScope struct {
	wg       sync.WaitGroup
	ctx      context.Context
	cancel   context.CancelFunc
	priority int
	sem      chan struct{}
}

type FreeholdJoinHandle[T any] struct {
	ch chan T
}

func freeholdSpawn[T any](wg *sync.WaitGroup, priority int, sem chan struct{}, f func() T) FreeholdJoinHandle[T] {
	wg.Add(1)
	ch := make(chan T, 1)
	taskFn := func() {
		defer wg.Done()
		if sem != nil {
			sem <- struct{}{}
			defer func() { <-sem }()
		}
		ch <- f()
	}
	getScheduler().Schedule(taskFn, priority)
	return FreeholdJoinHandle[T]{ch: ch}
}

func freeholdChannelSend[T any](sender chan<- T, value T) bool {
	sender <- value
	return true
}

func freeholdChannelTrySend[T any](sender chan<- T, value T) bool {
	select {
	case sender <- value:
		return true
	default:
		return false
	}
}

func freeholdChannelReceive[T any](receiver <-chan T) T {
	return <-receiver
}

func freeholdJSONString(value interface{}) string {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(data)
}

type freeholdJSONFieldSpec struct {
	typ reflect.Type
	min string
	max string
}

func freeholdRejectDuplicateJSONKeys(raw json.RawMessage, path string) error {
	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	decoder.UseNumber()
	if err := freeholdRejectDuplicateJSONKeysValue(decoder, path); err != nil {
		return err
	}
	if _, err := decoder.Token(); err != io.EOF {
		if err == nil {
			err = fmt.Errorf("unexpected trailing JSON value")
		}
		return err
	}
	return nil
}

func freeholdRejectDuplicateJSONKeysValue(decoder *json.Decoder, path string) error {
	token, err := decoder.Token()
	if err != nil {
		return err
	}
	delim, ok := token.(json.Delim)
	if !ok {
		return nil
	}
	switch delim {
	case '{':
		seen := map[string]bool{}
		for decoder.More() {
			keyToken, err := decoder.Token()
			if err != nil {
				return err
			}
			key, ok := keyToken.(string)
			if !ok {
				return fmt.Errorf("%s: expected object key", path)
			}
			if seen[key] {
				return fmt.Errorf("%s: duplicate object key %s", path, key)
			}
			seen[key] = true
			if err := freeholdRejectDuplicateJSONKeysValue(decoder, path+"."+key); err != nil {
				return err
			}
		}
		endToken, err := decoder.Token()
		if err != nil {
			return err
		}
		if end, ok := endToken.(json.Delim); !ok || end != '}' {
			return fmt.Errorf("%s: expected object end", path)
		}
	case '[':
		for decoder.More() {
			if err := freeholdRejectDuplicateJSONKeysValue(decoder, path+"[]"); err != nil {
				return err
			}
		}
		endToken, err := decoder.Token()
		if err != nil {
			return err
		}
		if end, ok := endToken.(json.Delim); !ok || end != ']' {
			return fmt.Errorf("%s: expected array end", path)
		}
	default:
		return fmt.Errorf("%s: unexpected JSON delimiter", path)
	}
	return nil
}

func freeholdValidateJSONValue(raw json.RawMessage, target reflect.Type, path string) error {
	return freeholdValidateJSONValueWithRange(raw, target, path, "", "")
}

func freeholdValidateJSONValueWithRange(raw json.RawMessage, target reflect.Type, path string, minValue string, maxValue string) error {
	if strings.TrimSpace(string(raw)) == "null" {
		return fmt.Errorf("%s: null not allowed", path)
	}
	switch target.Kind() {
	case reflect.Struct:
		var object map[string]json.RawMessage
		if err := json.Unmarshal(raw, &object); err != nil {
			return fmt.Errorf("%s: expected object", path)
		}
		fields := map[string]freeholdJSONFieldSpec{}
		for index := 0; index < target.NumField(); index++ {
			field := target.Field(index)
			name := field.Tag.Get("json")
			if name == "" {
				name = field.Name
			}
			fields[name] = freeholdJSONFieldSpec{typ: field.Type, min: field.Tag.Get("fh_min"), max: field.Tag.Get("fh_max")}
		}
		for name := range object {
			if _, ok := fields[name]; !ok {
				return fmt.Errorf("%s: unknown field %s", path, name)
			}
		}
		for name, fieldSpec := range fields {
			fieldRaw, ok := object[name]
			if !ok {
				return fmt.Errorf("%s: missing required field %s", path, name)
			}
			if err := freeholdValidateJSONValueWithRange(fieldRaw, fieldSpec.typ, path+"."+name, fieldSpec.min, fieldSpec.max); err != nil {
				return err
			}
		}
		return nil
	case reflect.Array:
		var items []json.RawMessage
		if err := json.Unmarshal(raw, &items); err != nil {
			return fmt.Errorf("%s: expected array", path)
		}
		if len(items) != target.Len() {
			return fmt.Errorf("%s: expected array length %d, got %d", path, target.Len(), len(items))
		}
		for _, item := range items {
			if err := freeholdValidateJSONValueWithRange(item, target.Elem(), path+"[]", minValue, maxValue); err != nil {
				return err
			}
		}
		return nil
	case reflect.String:
		var value string
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected String", path)
		}
		return nil
	case reflect.Bool:
		var value bool
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected Boolean", path)
		}
		return nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		var value json.Number
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected Integer", path)
		}
		if _, err := value.Int64(); err != nil {
			return fmt.Errorf("%s: expected Integer", path)
		}
		if minValue != "" {
			parsed, _ := value.Int64()
			minInt, err := strconv.ParseInt(minValue, 10, 64)
			if err != nil {
				return err
			}
			maxInt, err := strconv.ParseInt(maxValue, 10, 64)
			if err != nil {
				return err
			}
			if parsed < minInt || parsed > maxInt {
				return fmt.Errorf("%s: value %d out of range (%s..%s)", path, parsed, minValue, maxValue)
			}
		}
		return nil
	case reflect.Float32, reflect.Float64:
		var value float64
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected Double", path)
		}
		if minValue != "" {
			minFloat, err := strconv.ParseFloat(minValue, 64)
			if err != nil {
				return err
			}
			maxFloat, err := strconv.ParseFloat(maxValue, 64)
			if err != nil {
				return err
			}
			if value < minFloat || value > maxFloat {
				return fmt.Errorf("%s: value %v out of range (%s..%s)", path, value, minValue, maxValue)
			}
		}
		return nil
	default:
		return fmt.Errorf("%s: unsupported JSON target type %s", path, target.String())
	}
}

func HandleOne(ctx context.Context, server std_connect_grpc.ServerHandle) int64 {
	var accepted std_connect_grpc.ResultCallConnectError = std_connect_grpc.AcceptCall(ctx, server)
	if accepted.Ok == false {
		fmt.Println("gRPC server failed to accept call")
		return 1
	}
	var pending std_connect_grpc.Call = accepted.Value
	var parsed ResultUserRequestSchemaError = func() ResultUserRequestSchemaError {
		var value app_contract.UserRequest
		raw := []byte(pending.Payload)
		if err := freeholdRejectDuplicateJSONKeys(json.RawMessage(raw), "value"); err != nil {
			return ResultUserRequestSchemaError{Ok: false, Error: err.Error()}
		}
		if err := freeholdValidateJSONValue(json.RawMessage(raw), reflect.TypeOf(value), "value"); err != nil {
			return ResultUserRequestSchemaError{Ok: false, Error: err.Error()}
		}
		decoder := json.NewDecoder(strings.NewReader(string(raw)))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&value); err != nil {
			return ResultUserRequestSchemaError{Ok: false, Error: err.Error()}
		}
		var extra interface{}
		if err := decoder.Decode(&extra); err != io.EOF {
			if err == nil {
				err = fmt.Errorf("unexpected trailing JSON value")
			}
			return ResultUserRequestSchemaError{Ok: false, Error: err.Error()}
		}
		return ResultUserRequestSchemaError{Ok: true, Value: value}
	}()
	if parsed.Ok == false {
		fmt.Println("gRPC server received malformed request")
		return 1
	}
	var reply app_contract.UserResponse = app_contract.UserResponse{Name: "Ada"}
	var sent bool = std_connect_grpc.Respond(ctx, pending, freeholdJSONString(reply))
	if sent {
		return 0
	} else {
		return 1
	}
}

func ServerWorker(ctx context.Context, server std_connect_grpc.ServerHandle) int64 {
	var status int64 = HandleOne(ctx, server)
	return status
}

func ClientWorker(ctx context.Context, client std_connect_grpc.Client) int64 {
	var request app_contract.UserRequest = app_contract.UserRequest{Id: 42}
	var callResult std_connect_grpc.ResultUnaryReplyConnectError = std_connect_grpc.Unary(ctx, client, "GetUser", freeholdJSONString(request))
	if callResult.Ok == false {
		fmt.Println("gRPC unary GetUser failed")
		return 1
	}
	var response ResultUserResponseSchemaError = func() ResultUserResponseSchemaError {
		var value app_contract.UserResponse
		raw := []byte(callResult.Value.Payload)
		if err := freeholdRejectDuplicateJSONKeys(json.RawMessage(raw), "value"); err != nil {
			return ResultUserResponseSchemaError{Ok: false, Error: err.Error()}
		}
		if err := freeholdValidateJSONValue(json.RawMessage(raw), reflect.TypeOf(value), "value"); err != nil {
			return ResultUserResponseSchemaError{Ok: false, Error: err.Error()}
		}
		decoder := json.NewDecoder(strings.NewReader(string(raw)))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&value); err != nil {
			return ResultUserResponseSchemaError{Ok: false, Error: err.Error()}
		}
		var extra interface{}
		if err := decoder.Decode(&extra); err != io.EOF {
			if err == nil {
				err = fmt.Errorf("unexpected trailing JSON value")
			}
			return ResultUserResponseSchemaError{Ok: false, Error: err.Error()}
		}
		return ResultUserResponseSchemaError{Ok: true, Value: value}
	}()
	if response.Ok == false || response.Value.Name != "Ada" {
		fmt.Println("gRPC unary GetUser returned invalid response")
		return 1
	}
	fmt.Println("gRPC unary GetUser returned Ada")
	return 0
}

func RunDemo(ctx context.Context) int64 {
	var endpoint std_connect_common.Endpoint = std_connect_common.NewEndpoint("grpc", "127.0.0.1", 50551, "")
	var serveResult std_connect_grpc.ResultServerHandleConnectError = std_connect_grpc.Serve(endpoint)
	if serveResult.Ok == false {
		fmt.Println("gRPC server failed to bind")
		return 1
	}
	var server std_connect_grpc.ServerHandle = serveResult.Value
	var client std_connect_grpc.Client = std_connect_grpc.NewClient(endpoint)
	{
		demoScope := FreeholdScope{}
		demoScope.ctx, demoScope.cancel = context.WithCancel(ctx)
		demoScope.priority = 3
		demoScope.sem = nil
		defer demoScope.cancel()
		_ = demoScope
		var serverHandle FreeholdJoinHandle[int64] = freeholdSpawn[int64](&demoScope.wg, demoScope.priority, demoScope.sem, func() int64 { return ServerWorker(demoScope.ctx, server) })
		var clientHandle FreeholdJoinHandle[int64] = freeholdSpawn[int64](&demoScope.wg, demoScope.priority, demoScope.sem, func() int64 { return ClientWorker(demoScope.ctx, client) })
		var serverStatus int64 = <-serverHandle.ch
		var clientStatus int64 = <-clientHandle.ch
		std_connect_grpc.StopServer(server)
		if clientStatus == 0 && serverStatus == 0 {
			fmt.Println("Native gRPC server handled unary GetUser")
		}
		demoScope.wg.Wait()
		return serverStatus + clientStatus
	}
}

func Main(ctx context.Context) {
	var status int64 = RunDemo(ctx)
	if status == 0 {
		fmt.Println("Native gRPC unary demo finished successfully")
	} else {
		fmt.Println("Native gRPC unary demo finished with failure")
	}
}
