// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	math "freehold.local/math"
)

func Main() {
	root := math.Sqrt(9.0)
	if !(root == 3.0) {
		panic("freehold check failed")
	}
}