// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package mathcallsinsideexpressions

import (
	"math"
)

func Main() {
	total := math.Sqrt(float64(9.0)) + math.Pow(float64(2.0), float64(2.0))
	if !(total == 7.0) {
		panic("freehold check failed")
	}
}
