// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package mathminmax

import (
	"math"
)

func Main() {
	smaller := int64(math.Min(float64(2), float64(5)))
	larger := int64(math.Max(float64(2), float64(5)))
	decimal := math.Max(float64(2), float64(5.5))
	if !(smaller == 2) {
		panic("freehold check failed")
	}
	if !(larger == 5) {
		panic("freehold check failed")
	}
	if !(decimal == 5.5) {
		panic("freehold check failed")
	}
}
