// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package mathtrigfunctions

import (
	"math"
)

func Main() {
	var sine float64 = math.Sin(float64(0.0))
	var cosine float64 = math.Cos(float64(0.0))
	var tangent float64 = math.Tan(float64(0.0))
	if !(sine == 0.0) {
		panic("freehold check failed")
	}
	if !(cosine == 1.0) {
		panic("freehold check failed")
	}
	if !(tangent == 0.0) {
		panic("freehold check failed")
	}
}
