// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package mathabs

import (
	"math"
)

func Main() {
	whole := int64(math.Abs(float64(-3)))
	decimal := math.Abs(float64(-2.5))
	if !(whole == 3) {
		panic("freehold check failed")
	}
	if !(decimal == 2.5) {
		panic("freehold check failed")
	}
}
