// Code generated by Freehold gRPC Go binding codegen V1; DO NOT EDIT.
package grpcidl_streamingservice_grpc

import (
	"context"
	"errors"

	pb "freehold.local/grpc/grpcidl/streamingservicepb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

type RouteServiceHandler interface {
	GetRoute(request *pb.StreamRequest, stream pb.RouteService_GetRouteServer) error
	RecordRoute(stream pb.RouteService_RecordRouteServer) error
	Chat(stream pb.RouteService_ChatServer) error
}

type RouteServiceServer struct {
	pb.UnimplementedRouteServiceServer
	handler RouteServiceHandler
}

func NewRouteServiceServer(handler RouteServiceHandler) *RouteServiceServer {
	if handler == nil {
		panic("nil RouteServiceHandler")
	}
	return &RouteServiceServer{handler: handler}
}

func RegisterRouteServiceServer(registrar grpc.ServiceRegistrar, handler RouteServiceHandler) {
	pb.RegisterRouteServiceServer(registrar, NewRouteServiceServer(handler))
}

func (server *RouteServiceServer) GetRoute(request *pb.StreamRequest, stream pb.RouteService_GetRouteServer) error {
	err := server.handler.GetRoute(request, stream)
	if err != nil {
		return freeholdGrpcStatus(stream.Context(), err)
	}
	return nil
}

func (server *RouteServiceServer) RecordRoute(stream pb.RouteService_RecordRouteServer) error {
	err := server.handler.RecordRoute(stream)
	if err != nil {
		return freeholdGrpcStatus(stream.Context(), err)
	}
	return nil
}

func (server *RouteServiceServer) Chat(stream pb.RouteService_ChatServer) error {
	err := server.handler.Chat(stream)
	if err != nil {
		return freeholdGrpcStatus(stream.Context(), err)
	}
	return nil
}

type RouteServiceClient interface {
	GetRoute(ctx context.Context, request *pb.StreamRequest, opts ...grpc.CallOption) (pb.RouteService_GetRouteClient, error)
	RecordRoute(ctx context.Context, opts ...grpc.CallOption) (pb.RouteService_RecordRouteClient, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (pb.RouteService_ChatClient, error)
}

type routeServiceClient struct {
	client pb.RouteServiceClient
}

func NewRouteServiceClient(cc grpc.ClientConnInterface) RouteServiceClient {
	return &routeServiceClient{client: pb.NewRouteServiceClient(cc)}
}

func (c *routeServiceClient) GetRoute(ctx context.Context, request *pb.StreamRequest, opts ...grpc.CallOption) (pb.RouteService_GetRouteClient, error) {
	stream, err := c.client.GetRoute(ctx, request, opts...)
	if err != nil {
		return nil, freeholdGrpcStatus(ctx, err)
	}
	return stream, nil
}

func (c *routeServiceClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (pb.RouteService_RecordRouteClient, error) {
	stream, err := c.client.RecordRoute(ctx, opts...)
	if err != nil {
		return nil, freeholdGrpcStatus(ctx, err)
	}
	return stream, nil
}

func (c *routeServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (pb.RouteService_ChatClient, error) {
	stream, err := c.client.Chat(ctx, opts...)
	if err != nil {
		return nil, freeholdGrpcStatus(ctx, err)
	}
	return stream, nil
}

type FreeholdGrpcErrorMapping struct {
	Code     codes.Code
	Metadata map[string]string
}

var FreeholdGrpcErrorRegistry = map[string]FreeholdGrpcErrorMapping{}

func freeholdGrpcStatus(ctx context.Context, err error) error {
	if err == nil {
		return nil
	}
	var unwrappedErr = err
	for unwrappedErr != nil {
		msg := unwrappedErr.Error()
		if mapping, ok := FreeholdGrpcErrorRegistry[msg]; ok {
			if ctx != nil && len(mapping.Metadata) > 0 {
				md := metadata.New(mapping.Metadata)
				_ = grpc.SendHeader(ctx, md)
			}
			return status.Error(mapping.Code, msg)
		}
		unwrappedErr = errors.Unwrap(unwrappedErr)
	}
	if _, ok := status.FromError(err); ok {
		return err
	}
	if errors.Is(err, context.Canceled) {
		return status.Error(codes.Canceled, err.Error())
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return status.Error(codes.DeadlineExceeded, err.Error())
	}
	return status.Error(codes.Unknown, err.Error())
}
