// Code generated by Freehold gRPC Go binding codegen V1; DO NOT EDIT.
package grpcidl_unaryserviceprotofields_grpc

import (
	"context"
	"errors"

	pb "freehold.local/grpc/grpcidl/unaryserviceprotofieldspb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type UserServiceHandler interface {
	GetUser(ctx context.Context, request *pb.UserRequest) (*pb.UserReply, error)
}

type UserServiceServer struct {
	pb.UnimplementedUserServiceServer
	handler UserServiceHandler
}

func NewUserServiceServer(handler UserServiceHandler) *UserServiceServer {
	if handler == nil {
		panic("nil UserServiceHandler")
	}
	return &UserServiceServer{handler: handler}
}

func RegisterUserServiceServer(registrar grpc.ServiceRegistrar, handler UserServiceHandler) {
	pb.RegisterUserServiceServer(registrar, NewUserServiceServer(handler))
}

func (server *UserServiceServer) GetUser(ctx context.Context, request *pb.UserRequest) (*pb.UserReply, error) {
	response, err := server.handler.GetUser(ctx, request)
	if err != nil {
		return nil, freeholdGrpcStatus(err)
	}
	return response, nil
}

func freeholdGrpcStatus(err error) error {
	if err == nil {
		return nil
	}
	if _, ok := status.FromError(err); ok {
		return err
	}
	if errors.Is(err, context.Canceled) {
		return status.Error(codes.Canceled, err.Error())
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return status.Error(codes.DeadlineExceeded, err.Error())
	}
	return status.Error(codes.Unknown, err.Error())
}
