// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericmissingfunctiontypeargument

func Main() {
	x := IdentityInteger(1)
	_ = x
}

func IdentityInteger(x int64) int64 {
	return x
}
