// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package mathfloorceil

import (
	"math"
)

func Main() {
	var low int64 = int64(math.Floor(float64(2.8)))
	var high int64 = int64(math.Ceil(float64(2.2)))
	if !(low == 2) {
		panic("freehold check failed")
	}
	if !(high == 3) {
		panic("freehold check failed")
	}
}
