// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package mathtrigfunctions

import (
	"math"
)

func Main() {
	sine := math.Sin(float64(0.0))
	cosine := math.Cos(float64(0.0))
	tangent := math.Tan(float64(0.0))
	if !(sine == 0.0) {
		panic("freehold check failed")
	}
	if !(cosine == 1.0) {
		panic("freehold check failed")
	}
	if !(tangent == 0.0) {
		panic("freehold check failed")
	}
}
