// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package mathsqrtpow

import (
	"math"
)

func Main() {
	var root float64 = math.Sqrt(float64(9.0))
	var power float64 = math.Pow(float64(2.0), float64(3.0))
	if !(root == 3.0) {
		panic("freehold check failed")
	}
	if !(power == 8.0) {
		panic("freehold check failed")
	}
}
