// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_casereturn

func Score(choice int64) int64 {
	switch choice {
	case 1:
		var freeholdResult int64 = 10
		if !(choice == 1 && freeholdResult == 10 || choice == 2 && freeholdResult == 20 || choice != 1 && choice != 2 && freeholdResult == 0) {
			panic("freehold ensures contract failed")
		}
		return freeholdResult
	case 2:
		var freeholdResult int64 = 20
		if !(choice == 1 && freeholdResult == 10 || choice == 2 && freeholdResult == 20 || choice != 1 && choice != 2 && freeholdResult == 0) {
			panic("freehold ensures contract failed")
		}
		return freeholdResult
	default:
		var freeholdResult int64 = 0
		if !(choice == 1 && freeholdResult == 10 || choice == 2 && freeholdResult == 20 || choice != 1 && choice != 2 && freeholdResult == 0) {
			panic("freehold ensures contract failed")
		}
		return freeholdResult
	}
}

func Main() {
	if !(Score(2) == 20) {
		panic("freehold check failed")
	}
}
