// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_returnafterif

func Normalize(amount int64) int64 {
	if amount < 0 {
		if !(amount < 0) {
			panic("freehold check failed")
		}
	}
	return amount
}
