// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_whileinvariants

func Main() {
	amount := 0
	for amount < 2 {
		amount = amount + 1
	}
	if !(amount == 2) {
		panic("freehold check failed")
	}
}
