// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package concurrency_channeltrysendpos

import (
	"context"
	"runtime"
	"sync"
)

type freeholdTask struct {
	fn       func()
	priority int
}

type freeholdWorker struct {
	id         int
	mu         sync.Mutex
	q          []freeholdTask
	sch        *freeholdScheduler
	lastVictim int
}

type freeholdScheduler struct {
	mu          sync.Mutex
	workers     []*freeholdWorker
	workerCount int
	cond        *sync.Cond
	shutdown    bool
	nextWorker  int
}

var globalScheduler *freeholdScheduler
var schedulerOnce sync.Once

func getScheduler() *freeholdScheduler {
	schedulerOnce.Do(func() {
		globalScheduler = newScheduler(runtime.NumCPU())
	})
	return globalScheduler
}

func newScheduler(workerCount int) *freeholdScheduler {
	s := &freeholdScheduler{
		workerCount: workerCount,
	}
	s.cond = sync.NewCond(&s.mu)
	s.workers = make([]*freeholdWorker, workerCount)
	for i := 0; i < workerCount; i++ {
		s.workers[i] = &freeholdWorker{
			id:         i,
			sch:        s,
			lastVictim: i,
		}
	}
	for i := 0; i < workerCount; i++ {
		go s.workers[i].run()
	}
	return s
}

func (s *freeholdScheduler) Schedule(fn func(), priority int) {
	task := freeholdTask{fn: fn, priority: priority}
	s.mu.Lock()
	next := s.nextWorker
	s.nextWorker = (s.nextWorker + 1) % s.workerCount
	s.mu.Unlock()

	w := s.workers[next]
	w.mu.Lock()
	insertIndex := len(w.q)
	for i, t := range w.q {
		if task.priority > t.priority {
			insertIndex = i
			break
		}
	}
	w.q = append(w.q, freeholdTask{})
	copy(w.q[insertIndex+1:], w.q[insertIndex:])
	w.q[insertIndex] = task
	w.mu.Unlock()

	s.cond.Broadcast()
}

func (w *freeholdWorker) run() {
	s := w.sch
	for {
		var task freeholdTask
		found := false

		w.mu.Lock()
		if len(w.q) > 0 {
			task = w.q[0]
			w.q = w.q[1:]
			found = true
		}
		w.mu.Unlock()

		if !found {
			task, found = w.steal()
		}

		if !found {
			s.mu.Lock()
			for !s.shutdown {
				w.mu.Lock()
				if len(w.q) > 0 {
					task = w.q[0]
					w.q = w.q[1:]
					found = true
				}
				w.mu.Unlock()
				if found {
					break
				}

				task, found = w.steal()
				if found {
					break
				}

				s.cond.Wait()
			}
			s.mu.Unlock()
		}

		if s.shutdown {
			return
		}

		if found {
			task.fn()
		}
	}
}

func (w *freeholdWorker) steal() (freeholdTask, bool) {
	s := w.sch
	numWorkers := len(s.workers)
	if numWorkers <= 1 {
		return freeholdTask{}, false
	}
	w.lastVictim = (w.lastVictim + 1) % numWorkers
	if w.lastVictim == w.id {
		w.lastVictim = (w.lastVictim + 1) % numWorkers
	}
	victim := s.workers[w.lastVictim]

	victim.mu.Lock()
	defer victim.mu.Unlock()
	if len(victim.q) > 0 {
		task := victim.q[len(victim.q)-1]
		victim.q = victim.q[:len(victim.q)-1]
		return task, true
	}
	return freeholdTask{}, false
}

type Void struct{}

type FreeholdScope struct {
	wg       sync.WaitGroup
	ctx      context.Context
	cancel   context.CancelFunc
	priority int
	sem      chan struct{}
}

type FreeholdJoinHandle[T any] struct {
	ch chan T
}

func freeholdSpawn[T any](wg *sync.WaitGroup, priority int, sem chan struct{}, f func() T) FreeholdJoinHandle[T] {
	wg.Add(1)
	ch := make(chan T, 1)
	taskFn := func() {
		defer wg.Done()
		if sem != nil {
			sem <- struct{}{}
			defer func() { <-sem }()
		}
		ch <- f()
	}
	getScheduler().Schedule(taskFn, priority)
	return FreeholdJoinHandle[T]{ch: ch}
}

func freeholdJoin[T any](ctx context.Context, handle FreeholdJoinHandle[T]) T {
	select {
	case val := <-handle.ch:
		return val
	case <-ctx.Done():
		var zero T
		return zero
	}
}

func freeholdChannelSend[T any](sender chan<- T, value T) (ok bool) {
	defer func() {
		if r := recover(); r != nil {
			ok = false
		}
	}()
	sender <- value
	return true
}

func freeholdChannelTrySend[T any](sender chan<- T, value T) (ok bool) {
	defer func() {
		if r := recover(); r != nil {
			ok = false
		}
	}()
	select {
	case sender <- value:
		return true
	default:
		return false
	}
}

func freeholdChannelReceive[T any](ctx context.Context, receiver <-chan T) T {
	select {
	case val := <-receiver:
		return val
	case <-ctx.Done():
		var zero T
		return zero
	}
}

func ExecuteTrySend(ctx context.Context) bool {
	freeholdDefaultScope := FreeholdScope{}
	freeholdDefaultScope.ctx, freeholdDefaultScope.cancel = context.WithCancel(ctx)
	freeholdDefaultScope.priority = 3
	freeholdDefaultScope.sem = nil
	defer freeholdDefaultScope.cancel()
	_ = freeholdDefaultScope
	var chan_ chan int64 = make(chan int64, int(1))
	var sender chan<- int64 = chan_
	var first bool = freeholdChannelTrySend[int64](sender, 10)
	var second bool = freeholdChannelTrySend[int64](sender, 20)
	freeholdDefaultScope.wg.Wait()
	return first || second
}
