// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package concurrency_abortsyncpos

import (
	"context"
	"errors"
	"runtime"
	"sync"
)

type freeholdTask struct {
	fn       func()
	priority int
}

type freeholdWorker struct {
	id         int
	mu         sync.Mutex
	q          []freeholdTask
	sch        *freeholdScheduler
	lastVictim int
}

type freeholdScheduler struct {
	mu          sync.Mutex
	workers     []*freeholdWorker
	workerCount int
	cond        *sync.Cond
	shutdown    bool
	nextWorker  int
}

var globalScheduler *freeholdScheduler
var schedulerOnce sync.Once

func getScheduler() *freeholdScheduler {
	schedulerOnce.Do(func() {
		globalScheduler = newScheduler(runtime.NumCPU())
	})
	return globalScheduler
}

func newScheduler(workerCount int) *freeholdScheduler {
	s := &freeholdScheduler{
		workerCount: workerCount,
	}
	s.cond = sync.NewCond(&s.mu)
	s.workers = make([]*freeholdWorker, workerCount)
	for i := 0; i < workerCount; i++ {
		s.workers[i] = &freeholdWorker{
			id:         i,
			sch:        s,
			lastVictim: i,
		}
	}
	for i := 0; i < workerCount; i++ {
		go s.workers[i].run()
	}
	return s
}

func (s *freeholdScheduler) Schedule(fn func(), priority int) {
	task := freeholdTask{fn: fn, priority: priority}
	s.mu.Lock()
	next := s.nextWorker
	s.nextWorker = (s.nextWorker + 1) % s.workerCount
	s.mu.Unlock()

	w := s.workers[next]
	w.mu.Lock()
	insertIndex := len(w.q)
	for i, t := range w.q {
		if task.priority > t.priority {
			insertIndex = i
			break
		}
	}
	w.q = append(w.q, freeholdTask{})
	copy(w.q[insertIndex+1:], w.q[insertIndex:])
	w.q[insertIndex] = task
	w.mu.Unlock()

	s.cond.Broadcast()
}

func (w *freeholdWorker) run() {
	s := w.sch
	for {
		var task freeholdTask
		found := false

		w.mu.Lock()
		if len(w.q) > 0 {
			task = w.q[0]
			w.q = w.q[1:]
			found = true
		}
		w.mu.Unlock()

		if !found {
			task, found = w.steal()
		}

		if !found {
			s.mu.Lock()
			for !s.shutdown {
				w.mu.Lock()
				if len(w.q) > 0 {
					task = w.q[0]
					w.q = w.q[1:]
					found = true
				}
				w.mu.Unlock()
				if found {
					break
				}

				task, found = w.steal()
				if found {
					break
				}

				s.cond.Wait()
			}
			s.mu.Unlock()
		}

		if s.shutdown {
			return
		}

		if found {
			task.fn()
		}
	}
}

func (w *freeholdWorker) steal() (freeholdTask, bool) {
	s := w.sch
	numWorkers := len(s.workers)
	if numWorkers <= 1 {
		return freeholdTask{}, false
	}
	w.lastVictim = (w.lastVictim + 1) % numWorkers
	if w.lastVictim == w.id {
		w.lastVictim = (w.lastVictim + 1) % numWorkers
	}
	victim := s.workers[w.lastVictim]

	victim.mu.Lock()
	defer victim.mu.Unlock()
	if len(victim.q) > 0 {
		task := victim.q[len(victim.q)-1]
		victim.q = victim.q[:len(victim.q)-1]
		return task, true
	}
	return freeholdTask{}, false
}

type FreeholdScope struct {
	wg       sync.WaitGroup
	ctx      context.Context
	cancel   context.CancelFunc
	priority int
	sem      chan struct{}
}

type FreeholdJoinHandle[T any] struct {
	ch chan T
}

func freeholdSpawn[T any](wg *sync.WaitGroup, priority int, sem chan struct{}, f func() T) FreeholdJoinHandle[T] {
	wg.Add(1)
	ch := make(chan T, 1)
	taskFn := func() {
		defer wg.Done()
		if sem != nil {
			sem <- struct{}{}
			defer func() { <-sem }()
		}
		ch <- f()
	}
	getScheduler().Schedule(taskFn, priority)
	return FreeholdJoinHandle[T]{ch: ch}
}

func freeholdChannelSend[T any](sender chan<- T, value T) bool {
	sender <- value
	return true
}

func freeholdChannelTrySend[T any](sender chan<- T, value T) bool {
	select {
	case sender <- value:
		return true
	default:
		return false
	}
}

func freeholdChannelReceive[T any](receiver <-chan T) T {
	return <-receiver
}

const VerificationError = "VerificationError"

func Compute(ctx context.Context, val int64) int64 {
	if !(val > 0) {
		panic("freehold requires contract failed")
	}
	return val * 2
}

func ExecuteTask(ctx context.Context, input int64) (int64, error) {
	if !(input > 10) {
		panic("freehold requires contract failed")
	}
	chan_ := 5
	select_ := 10
	var isValid bool = input > 0 == (chan_ < select_)
	if !(isValid == true) {
		panic("freehold check failed")
	}
	{
		sc := FreeholdScope{}
		sc.ctx, sc.cancel = context.WithCancel(ctx)
		sc.priority = 3
		sc.sem = nil
		defer sc.cancel()
		_ = sc
		var handle FreeholdJoinHandle[int64] = freeholdSpawn[int64](&sc.wg, sc.priority, sc.sem, func() int64 { return Compute(sc.ctx, input) })
		var res int64 = <-handle.ch
		if res > 100 {
			sc.wg.Wait()
			return 0, errors.New(VerificationError)
		}
		sc.wg.Wait()
		return res, nil
	}
}
