// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package concurrency_asyncawait

import (
	"context"
)

func Fetch(ctx context.Context) int64 {
	return 42
}

func Compute(ctx context.Context) int64 {
	var item int64 = Fetch(ctx)
	return item
}
