// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package jsonfieldnameroundtrip

import (
	"encoding/json"
	"fmt"
	"io"
	"reflect"
	"strings"
)

type ResultPersonSchemaError struct {
	Ok    bool
	Value Person
	Error string
}

func freeholdJSONString(value interface{}) string {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(data)
}

func freeholdValidateJSONValue(raw json.RawMessage, target reflect.Type, path string) error {
	switch target.Kind() {
	case reflect.Struct:
		var object map[string]json.RawMessage
		if err := json.Unmarshal(raw, &object); err != nil {
			return fmt.Errorf("%s: expected object", path)
		}
		fields := map[string]reflect.Type{}
		for index := 0; index < target.NumField(); index++ {
			field := target.Field(index)
			name := field.Tag.Get("json")
			if name == "" {
				name = field.Name
			}
			fields[name] = field.Type
		}
		for name := range object {
			if _, ok := fields[name]; !ok {
				return fmt.Errorf("%s: unknown field %s", path, name)
			}
		}
		for name, fieldType := range fields {
			fieldRaw, ok := object[name]
			if !ok {
				return fmt.Errorf("%s: missing required field %s", path, name)
			}
			if err := freeholdValidateJSONValue(fieldRaw, fieldType, path+"."+name); err != nil {
				return err
			}
		}
		return nil
	case reflect.Array:
		var items []json.RawMessage
		if err := json.Unmarshal(raw, &items); err != nil {
			return fmt.Errorf("%s: expected array", path)
		}
		if len(items) != target.Len() {
			return fmt.Errorf("%s: expected array length %d, got %d", path, target.Len(), len(items))
		}
		for _, item := range items {
			if err := freeholdValidateJSONValue(item, target.Elem(), path+"[]"); err != nil {
				return err
			}
		}
		return nil
	case reflect.String:
		var value string
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected String", path)
		}
		return nil
	case reflect.Bool:
		var value bool
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected Boolean", path)
		}
		return nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		var value json.Number
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected Integer", path)
		}
		if _, err := value.Int64(); err != nil {
			return fmt.Errorf("%s: expected Integer", path)
		}
		return nil
	case reflect.Float32, reflect.Float64:
		var value float64
		if err := json.Unmarshal(raw, &value); err != nil {
			return fmt.Errorf("%s: expected Double", path)
		}
		return nil
	default:
		return fmt.Errorf("%s: unsupported JSON target type %s", path, target.String())
	}
}

type Person struct {
	FirstName string `json:"firstName"`
	Age       int64  `json:"age"`
}

func Main() {
	var text string = "{\"firstName\":\"Ada\",\"age\":37}"
	var parsed ResultPersonSchemaError = func() ResultPersonSchemaError {
		var value Person
		raw := []byte(text)
		if err := freeholdValidateJSONValue(json.RawMessage(raw), reflect.TypeOf(value), "value"); err != nil {
			return ResultPersonSchemaError{Ok: false, Error: err.Error()}
		}
		decoder := json.NewDecoder(strings.NewReader(string(raw)))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&value); err != nil {
			return ResultPersonSchemaError{Ok: false, Error: err.Error()}
		}
		var extra interface{}
		if err := decoder.Decode(&extra); err != io.EOF {
			if err == nil {
				err = fmt.Errorf("unexpected trailing JSON value")
			}
			return ResultPersonSchemaError{Ok: false, Error: err.Error()}
		}
		return ResultPersonSchemaError{Ok: true, Value: value}
	}()
	if !(parsed.Ok) {
		panic("freehold check failed")
	}
	if !(parsed.Value.FirstName == "Ada") {
		panic("freehold check failed")
	}
	var encoded string = freeholdJSONString(parsed.Value)
	if !(encoded == text) {
		panic("freehold check failed")
	}
}
