// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package banking_proofs

func BalanceNeverNegative() bool {
	var freeholdResult bool = true
	if !(freeholdResult == true) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}
