// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package test_array_quantifiers

func VerifyQuantifiers(arr [3]int64) bool {
	var allPositive bool = func() bool {
		for i := int64(0); i <= int64(2); i++ {
			if !(arr[i] >= 0) {
				return false
			}
		}
		return true
	}()
	var someNonNegative bool = func() bool {
		for i := int64(0); i <= int64(2); i++ {
			if arr[i] == 0 {
				return true
			}
		}
		return false
	}()
	return allPositive && someNonNegative
}
