// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package abortpropagationok

import (
	"errors"
)

const NotFound = "NotFound"

func Read(id int64) (int64, error) {
	if id == 0 {
		return 0, errors.New(NotFound)
	}
	return id, nil
}

func Load(id int64) (int64, error) {
	value, err := Read(id)
	if err != nil {
		return 0, err
	}
	return value, nil
}
