// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_booleancase

func Main() {
	active := true
	switch active {
	case true:
		if !(active) {
			panic("freehold check failed")
		}
	case false:
		if !(active == false) {
			panic("freehold check failed")
		}
	default:
		if !(true) {
			panic("freehold check failed")
		}
	}
}
