// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_casereturn

func Score(choice int64) int64 {
	switch choice {
	case 1:
		return 10
	case 2:
		return 20
	default:
		return 0
	}
}

func Main() {
	if !(Score(2) == 20) {
		panic("freehold check failed")
	}
}
