// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_ifelsereturn

func Classify(amount int64) int64 {
	if amount > 0 {
		var freeholdResult int64 = 1
		if !(amount > 0 && freeholdResult == 1 || amount <= 0 && freeholdResult == 0) {
			panic("freehold ensures contract failed")
		}
		return freeholdResult
	} else {
		var freeholdResult int64 = 0
		if !(amount > 0 && freeholdResult == 1 || amount <= 0 && freeholdResult == 0) {
			panic("freehold ensures contract failed")
		}
		return freeholdResult
	}
}

func Main() {
	if !(Classify(1) == 1) {
		panic("freehold check failed")
	}
}
