// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_ifelsereturn

func Classify(amount int64) int64 {
	if amount > 0 {
		return 1
	} else {
		return 0
	}
}

func Main() {
	if !(Classify(1) == 1) {
		panic("freehold check failed")
	}
}
