// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_nestededges

func Main() {
	amount := 1
	if amount == 1 {
		switch amount {
		case 1:
			if !(true) {
				panic("freehold check failed")
			}
		default:
			if !(false == false) {
				panic("freehold check failed")
			}
		}
	} else {
		for amount > 0 {
			amount = amount - 1
		}
	}
	if !(amount == 1) {
		panic("freehold check failed")
	}
}
