// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package control_whilezero

func Main() {
	amount := 0
	for amount > 0 {
		amount = amount - 1
	}
	if !(amount == 0) {
		panic("freehold check failed")
	}
}
