// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package fieldassignmentstatement

type Account struct {
	Id     int64
	Active bool
}

func Main() {
	account := Account{Id: 1, Active: false}
	account.Active = true
	if !(account.Active) {
		panic("freehold check failed")
	}
}
