// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package ifstatement

func Main() {
	amount := 1
	if amount == 1 {
		if !(true) {
			panic("freehold check failed")
		}
	} else {
		if !(false == true) {
			panic("freehold check failed")
		}
	}
}
