// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package whilestatement

func Main() {
	amount := 3
	for amount > 0 {
		amount = amount - 1
	}
	if !(amount == 0) {
		panic("freehold check failed")
	}
}
