// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericrecordbox

func Main() {
	var b GenericRecordBoxBoxInteger = GenericRecordBoxBoxInteger{Item: 1}
	if !(b.Item == 1) {
		panic("freehold check failed")
	}
}
