// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericfunctionidentity

func Main() {
	x := IdentityInteger(1)
	text := IdentityString("ok")
	if !(x == 1) {
		panic("freehold check failed")
	}
	if !(text == "ok") {
		panic("freehold check failed")
	}
}

func IdentityInteger(x int64) int64 {
	return x
}

func IdentityString(x string) string {
	return x
}
