// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_contract

type UserRequest struct {
	Id int64 `json:"id"`
}

type UserResponse struct {
	Name string `json:"name"`
}

// Service UserService is emitted through the generated gRPC binding file.
