// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package std_connect_common

const ConnectError = "ConnectError"

type Endpoint struct {
	Scheme     string `json:"scheme"`
	Host       string `json:"host"`
	Port       int64  `json:"port"`
	PathPrefix string `json:"path_prefix"`
}

type Header struct {
	Name        string `json:"name"`
	HeaderValue string `json:"header_value"`
}

type Headers struct {
	Accept        string `json:"accept"`
	ContentType   string `json:"content_type"`
	Authorization string `json:"authorization"`
	RequestId     string `json:"request_id"`
}

type Timeout struct {
	Milliseconds int64 `json:"milliseconds"`
}

type Deadline struct {
	EpochMillis int64 `json:"epoch_millis"`
}

type Body struct {
	Text        string `json:"text"`
	ContentType string `json:"content_type"`
}

func NewEndpoint(scheme string, host string, port int64, pathPrefix string) Endpoint {
	return Endpoint{Scheme: scheme, Host: host, Port: port, PathPrefix: pathPrefix}
}

func LocalhostHttp(port int64, pathPrefix string) Endpoint {
	return NewEndpoint("http", "127.0.0.1", port, pathPrefix)
}

func NewHeader(name string, headerValue string) Header {
	return Header{Name: name, HeaderValue: headerValue}
}

func EmptyHeaders() Headers {
	return Headers{Accept: "", ContentType: "", Authorization: "", RequestId: ""}
}

func JsonHeaders() Headers {
	return Headers{Accept: "application/json", ContentType: "application/json", Authorization: "", RequestId: ""}
}

func WithRequestId(headers Headers, requestId string) Headers {
	return Headers{Accept: headers.Accept, ContentType: headers.ContentType, Authorization: headers.Authorization, RequestId: requestId}
}

func WithAuthorization(headers Headers, authorization string) Headers {
	return Headers{Accept: headers.Accept, ContentType: headers.ContentType, Authorization: authorization, RequestId: headers.RequestId}
}

func EmptyBody() Body {
	return Body{Text: "", ContentType: ""}
}

func TextBody(text string) Body {
	return Body{Text: text, ContentType: "text/plain"}
}

func JsonBody(text string) Body {
	return Body{Text: text, ContentType: "application/json"}
}

func TimeoutMillis(milliseconds int64) Timeout {
	return Timeout{Milliseconds: milliseconds}
}

func NoDeadline() Deadline {
	return Deadline{EpochMillis: 0}
}
