// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package monomorphizedinferenceandconstraintspos

func Main() {
	var x int64 = MonomorphizedInferenceAndConstraintsPosMinValInteger(10, 20)
	_ = x
	var y float64 = MonomorphizedInferenceAndConstraintsPosMinValDouble(3.14, 2.71)
	_ = y
	var z int64 = MonomorphizedInferenceAndConstraintsPosAddValInteger(40, 2)
	_ = z
	var w float64 = MonomorphizedInferenceAndConstraintsPosAddValDouble(1.5, 2.5)
	_ = w
	MonomorphizedInferenceAndConstraintsPosLogAndSwapInteger(10, 20)
	MonomorphizedInferenceAndConstraintsPosLogAndSwapDouble(3.14, 2.71)
}

func MonomorphizedInferenceAndConstraintsPosAddValDouble(a float64, b float64) float64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	return a + b
}

func MonomorphizedInferenceAndConstraintsPosAddValInteger(a int64, b int64) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	return a + b
}

func MonomorphizedInferenceAndConstraintsPosLogAndSwapDouble(a float64, b float64) {
	if !(true) {
		panic("freehold requires contract failed")
	}
	var temp float64 = a
	var first float64 = b
	_ = first
	var second float64 = temp
	_ = second
}

func MonomorphizedInferenceAndConstraintsPosLogAndSwapInteger(a int64, b int64) {
	if !(true) {
		panic("freehold requires contract failed")
	}
	var temp int64 = a
	var first int64 = b
	_ = first
	var second int64 = temp
	_ = second
}

func MonomorphizedInferenceAndConstraintsPosMinValDouble(a float64, b float64) float64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a < b {
		return a
	}
	return b
}

func MonomorphizedInferenceAndConstraintsPosMinValInteger(a int64, b int64) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a < b {
		return a
	}
	return b
}
