// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package monomorphizedinferenceandconstraintspos

func Main() {
	var x int64 = MinValInteger(10, 20)
	_ = x
	var y float64 = MinValDouble(3.14, 2.71)
	_ = y
	var z int64 = AddValInteger(40, 2)
	_ = z
	var w float64 = AddValDouble(1.5, 2.5)
	_ = w
	LogAndSwapInteger(10, 20)
	LogAndSwapDouble(3.14, 2.71)
}

func AddValDouble(a float64, b float64) float64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	return a + b
}

func AddValInteger(a int64, b int64) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	return a + b
}

func LogAndSwapDouble(a float64, b float64) {
	if !(true) {
		panic("freehold requires contract failed")
	}
	var temp float64 = a
	var first float64 = b
	_ = first
	var second float64 = temp
	_ = second
}

func LogAndSwapInteger(a int64, b int64) {
	if !(true) {
		panic("freehold requires contract failed")
	}
	var temp int64 = a
	var first int64 = b
	_ = first
	var second int64 = temp
	_ = second
}

func MinValDouble(a float64, b float64) float64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a < b {
		return a
	}
	return b
}

func MinValInteger(a int64, b int64) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a < b {
		return a
	}
	return b
}
