// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package arrayquantifier

func Main() {
	var values [3]int64 = [3]int64{5, 5, 5}
	_ = values
	if !(func() bool {
		for i := int64(0); i <= int64(2); i++ {
			if !(values[i] == 5) {
				return false
			}
		}
		return true
	}()) {
		panic("freehold check failed")
	}
	if !(func() bool {
		for i := int64(0); i <= int64(2); i++ {
			if values[i] == 5 {
				return true
			}
		}
		return false
	}()) {
		panic("freehold check failed")
	}
}
