// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package partner_reports

import (
	partner_shared "freehold.local/partner/shared"
)

type ResultPartnerReportNotFound struct {
	Ok    bool
	Value PartnerReport
	Error string
}

type PartnerReport struct {
	Order partner_shared.Order   `json:"order"`
	Depot partner_shared.Address `json:"depot"`
}

func FindPartner(seed int64) ResultPartnerReportNotFound {
	if !(seed > 0) {
		panic("freehold requires contract failed")
	}
	depot := partner_shared.MakeAddress(7, "Hamburg")
	order := partner_shared.MakeOrder(seed+100, depot)
	freeholdResult := ResultPartnerReportNotFound{Ok: true, Value: PartnerReport{Order: order, Depot: depot}}
	if !(freeholdResult.Value.Order.Address.CityId == 7) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func LoadPartner(seed int64) PartnerReport {
	if !(seed > 0) {
		panic("freehold requires contract failed")
	}
	outcome := FindPartner(seed)
	return outcome.Value
}
