// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package domain_types

type Account struct {
	Id int64 `json:"id"`
}

func MakeAccount() Account {
	return Account{Id: 1}
}

func IsValid(account Account) bool {
	return account.Id == 1
}
