// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package domain_types

type Account struct {
	Id int64 `json:"id"`
}

func MakeAccount() Account {
	var freeholdResult Account = Account{Id: 1}
	if !(freeholdResult.Id == 1) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func IsValid(account Account) bool {
	var freeholdResult bool = account.Id == 1
	if !(freeholdResult == (account.Id == 1)) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}
