// Code generated by Freehold Go codegen V1 gRPC project stubs; DO NOT EDIT.
package app_contractpb

import (
	"context"
	"encoding/json"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/encoding"
	"google.golang.org/grpc/status"
)

type UserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (*UserRequest) Reset()         {}
func (*UserRequest) String() string { return "" }
func (*UserRequest) ProtoMessage()  {}

type UserResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
}

func (*UserResponse) Reset()         {}
func (*UserResponse) String() string { return "" }
func (*UserResponse) ProtoMessage()  {}

type UserServiceServer interface {
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
}

type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUser(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}

type UserServiceClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userserviceClient{cc}
}

func (c *userserviceClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	opts = append(opts, grpc.CallContentSubtype("json"))
	err := c.cc.Invoke(ctx, "/app.contract.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.contract.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func RegisterUserServiceServer(registrar grpc.ServiceRegistrar, server UserServiceServer) {
	registrar.RegisterService(&UserService_ServiceDesc, server)
}

var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.contract.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "",
}

type jsonCodec struct{}

func (jsonCodec) Marshal(v interface{}) ([]byte, error) {
	return json.Marshal(v)
}

func (jsonCodec) Unmarshal(data []byte, v interface{}) error {
	return json.Unmarshal(data, v)
}

func (jsonCodec) Name() string {
	return "json"
}

func init() {
	if encoding.GetCodec("json") == nil {
		encoding.RegisterCodec(jsonCodec{})
	}
}
