// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package bigfloatoperations

import (
	"math/big"
	"strings"
)

func freeholdBigInt(text string) *big.Int {
	value, ok := new(big.Int).SetString(text, 10)
	if !ok {
		panic("invalid BigInteger literal")
	}
	return value
}

func freeholdBigFloat(text string, precision int64) *big.Float {
	value, ok := new(big.Float).SetPrec(uint(precision)).SetString(text)
	if !ok {
		panic("invalid BigFloat literal")
	}
	return value
}

func freeholdBigFloatFromInteger(value *big.Int, precision int64) *big.Float {
	return new(big.Float).SetPrec(uint(precision)).SetInt(value)
}

func freeholdBigFloatAbs(value *big.Float) *big.Float {
	result := new(big.Float).SetPrec(value.Prec()).Set(value)
	if result.Sign() < 0 {
		result.Neg(result)
	}
	return result
}

func Main() {
	x := freeholdBigFloat("10005", 256)
	root := new(big.Float).SetPrec(x.Prec()).Sqrt(x)
	scaled := new(big.Float).SetPrec(freeholdBigFloat("426880", 256).Prec()).Mul(freeholdBigFloat("426880", 256), root)
	text := scaled.Text('f', int(5))
	if !(int64(strings.Index(text, ".")) > 0) {
		panic("freehold check failed")
	}
}
