// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericinferencesuccess

func Main() {
	x := MaxInteger(3, 4)
	_ = x
	y := MaxDouble(5.0, 2.0)
	_ = y
}

func MaxDouble(a float64, b float64) float64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a > b {
		return a
	} else {
		return b
	}
}

func MaxInteger(a int64, b int64) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a > b {
		return a
	} else {
		return b
	}
}
