// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericinferencesuccess

func Main() {
	var x int64 = GenericInferenceSuccessMaxInteger(3, 4)
	_ = x
	var y float64 = GenericInferenceSuccessMaxDouble(5.0, 2.0)
	_ = y
}

func GenericInferenceSuccessMaxDouble(a float64, b float64) float64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a > b {
		return a
	} else {
		return b
	}
}

func GenericInferenceSuccessMaxInteger(a int64, b int64) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	if a > b {
		return a
	} else {
		return b
	}
}
