// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericfunctionunwrapbox

func Main() {
	var b GenericFunctionUnwrapBoxBoxInteger = GenericFunctionUnwrapBoxBoxInteger{Item: 1}
	var x int64 = GenericFunctionUnwrapBoxUnwrapInteger(b)
	if !(x == 1) {
		panic("freehold check failed")
	}
}

func GenericFunctionUnwrapBoxUnwrapInteger(box BoxInteger) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	var freeholdResult int64 = box.Item
	if !(freeholdResult == box.Item) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}
