// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericfunctionunwrapbox

func Main() {
	b := Box_Int64{Item: 1}
	x := UnwrapInteger(b)
	if !(x == 1) {
		panic("freehold check failed")
	}
}

type BoxInteger struct {
	Item int64 `json:"item"`
}

type BoxT struct {
	Item T `json:"item"`
}

func UnwrapInteger(box Box_Int64) int64 {
	return box.Item
}
