// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericfunctionidentity

func Main() {
	var x int64 = GenericFunctionIdentityIdentityInteger(1)
	var text string = GenericFunctionIdentityIdentityString("ok")
	if !(x == 1) {
		panic("freehold check failed")
	}
	if !(text == "ok") {
		panic("freehold check failed")
	}
}

func GenericFunctionIdentityIdentityInteger(x int64) int64 {
	if !(true) {
		panic("freehold requires contract failed")
	}
	var freeholdResult int64 = x
	if !(freeholdResult == x) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func GenericFunctionIdentityIdentityString(x string) string {
	if !(true) {
		panic("freehold requires contract failed")
	}
	var freeholdResult string = x
	if !(freeholdResult == x) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}
