// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package genericmissingfunctiontypeargument

func Main() {
	var x int64 = GenericMissingFunctionTypeArgumentIdentityInteger(1)
	_ = x
}

func GenericMissingFunctionTypeArgumentIdentityInteger(x int64) int64 {
	return x
}
