// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	domain_types "freehold.local/domain/types"
)

func AccountOk(account domain_types.Account) bool {
	var freeholdResult bool = account.Id == 1
	if !(freeholdResult == (account.Id == 1)) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func Main() {
	var account domain_types.Account = domain_types.MakeAccount()
	if !(AccountOk(account)) {
		panic("freehold check failed")
	}
	if !(domain_types.IsValid(account)) {
		panic("freehold check failed")
	}
}
