// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	domain_types "freehold.local/domain/types"
)

func AccountOk(account domain_types.Account) bool {
	return account.Id == 1
}

func Main() {
	account := domain_types.MakeAccount()
	if !(AccountOk(account)) {
		panic("freehold check failed")
	}
	if !(domain_types.IsValid(account)) {
		panic("freehold check failed")
	}
}
