// Code generated by Freehold gRPC Go runtime glue codegen V1; DO NOT EDIT.
package app_contract_grpc

import (
	"context"
	"encoding/json"

	pb "freehold.local/grpc/app/contractpb"
	grpcrt "freehold.local/std/connect/grpc"
	"google.golang.org/grpc"
)

type userServiceRuntimeAdapter struct{}

func (userServiceRuntimeAdapter) GetUser(ctx context.Context, request *pb.UserRequest) (*pb.UserResponse, error) {
	payload, err := json.Marshal(request)
	if err != nil {
		return nil, err
	}
	reply := make(chan string, 1)
	grpcrt.EnqueueUnaryCall(&grpcrt.GrpcUnaryCall{Method: "GetUser", Payload: string(payload), Reply: reply})
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	case responsePayload := <-reply:
		response := new(pb.UserResponse)
		if err := json.Unmarshal([]byte(responsePayload), response); err != nil {
			return nil, err
		}
		return response, nil
	}
}

func init() {
	grpcrt.RegisterServiceRegistrar(func(server *grpc.Server) {
		RegisterUserServiceServer(server, userServiceRuntimeAdapter{})
	})
	grpcrt.RegisterClientDispatcher("GetUser", func(ctx context.Context, cc grpc.ClientConnInterface, payload string) (string, error) {
		request := new(pb.UserRequest)
		if err := json.Unmarshal([]byte(payload), request); err != nil {
			return "", err
		}
		client := NewUserServiceClient(cc)
		response, err := client.GetUser(ctx, request)
		if err != nil {
			return "", err
		}
		encoded, err := json.Marshal(response)
		if err != nil {
			return "", err
		}
		return string(encoded), nil
	})
}
