// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package callstatement

func Accept(flag bool) {
	if !(flag == true) {
		panic("freehold requires contract failed")
	}
	if !(flag) {
		panic("freehold check failed")
	}
}

func Main() {
	Accept(true)
}
