// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package casestatement

func Main() {
	choice := 1
	switch choice {
	case 1:
		if !(true) {
			panic("freehold check failed")
		}
	case 2:
		if !(true) {
			panic("freehold check failed")
		}
	default:
		if !(true) {
			panic("freehold check failed")
		}
	}
}
