// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package commentmarkersinsidestrings

func Text() string {
	return "not -- a comment and not /* a block */"
}

func Main() {
	textValue := Text()
	if !(textValue == "not -- a comment and not /* a block */") {
		panic("freehold check failed")
	}
}
