// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package aliasarraysignatureusage

type Money int64

func Values() [3]Money {
	return [3]Money{1, 2, 3}
}

func Main() {
	amounts := Values()
	amount := amounts[0]
	if !(amount == 1) {
		panic("freehold check failed")
	}
}
