// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package domestic_shared

type Address struct {
	CityId int64  `json:"city_id"`
	Label  string `json:"label"`
}

type Order struct {
	Id      int64   `json:"id"`
	Address Address `json:"address"`
}

const NotFound = "NotFound"

func MakeAddress(cityId int64, label string) Address {
	return Address{CityId: cityId, Label: label}
}

func MakeOrder(id int64, address Address) Order {
	return Order{Id: id, Address: address}
}
