// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package domestic_reports

import (
	domestic_shared "freehold.local/domestic/shared"
)

type ResultDomesticReportNotFound struct {
	Ok    bool
	Value DomesticReport
	Error string
}

type DomesticReport struct {
	Order domestic_shared.Order   `json:"order"`
	Depot domestic_shared.Address `json:"depot"`
}

func FindDomestic(seed int64) ResultDomesticReportNotFound {
	if !(seed > 0) {
		panic("freehold requires contract failed")
	}
	depot := domestic_shared.MakeAddress(42, "Berlin")
	order := domestic_shared.MakeOrder(seed, depot)
	freeholdResult := ResultDomesticReportNotFound{Ok: true, Value: DomesticReport{Order: order, Depot: depot}}
	if !(freeholdResult.Value.Order.Address.CityId == 42) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func LoadDomestic(seed int64) DomesticReport {
	if !(seed > 0) {
		panic("freehold requires contract failed")
	}
	outcome := FindDomestic(seed)
	return outcome.Value
}
