// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package qualified_stringbuiltins

import (
	"strings"
)

func Main() {
	var greeting string = "Vera" + "Flow"
	var index int64 = int64(strings.Index(greeting, "Flow"))
	if !(index == 4) {
		panic("freehold check failed")
	}
}
