// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package qualified_stringbuiltins

import (
	"strings"
)

func Main() {
	greeting := "Vera" + "Flow"
	index := int64(strings.Index(greeting, "Flow"))
	if !(index == 4) {
		panic("freehold check failed")
	}
}
