// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package app_main

import (
	domestic_reports "freehold.local/domestic/reports"
	partner_reports "freehold.local/partner/reports"
)

func TotalCityIds(seed int64) int64 {
	if !(seed > 0) {
		panic("freehold requires contract failed")
	}
	var domestic domestic_reports.DomesticReport = domestic_reports.LoadDomestic(seed)
	var partner partner_reports.PartnerReport = partner_reports.LoadPartner(seed)
	if !(domestic.Order.Address.CityId == domestic.Depot.CityId) {
		panic("freehold check failed")
	}
	if !(partner.Order.Address.CityId == partner.Depot.CityId) {
		panic("freehold check failed")
	}
	return domestic.Order.Address.CityId + partner.Order.Address.CityId
}
