// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package functioncallexpressionvalue

func One() int64 {
	var freeholdResult int64 = 1
	if !(freeholdResult == 1) {
		panic("freehold ensures contract failed")
	}
	return freeholdResult
}

func Main() {
	if !(One()+1 == 2) {
		panic("freehold check failed")
	}
}
