// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package functioncallexpressionvalue

func One() int64 {
	return 1
}

func Main() {
	if !(One()+1 == 2) {
		panic("freehold check failed")
	}
}
