// Code generated by Freehold Go codegen V1; DO NOT EDIT.
package recordfieldexpression

type Account struct {
	Id     int64 `json:"id"`
	Active bool  `json:"active"`
}

func Main() {
	var account Account = Account{Id: 1, Active: true}
	if !(account.Id == 1 && account.Active) {
		panic("freehold check failed")
	}
}
